### ISSUE TITLE
analysis.connectedPoints not working

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vtkplotter#101]
Hi, 

I'm trying to use `connectedPoints` to isolate a cluster of points withing a large and sparse cloud of points, but I get an error when i try it.

```
injection = connectedPoints(Points(pts2), radius=10, mode=2)
```
where `pts2` is a list of points coordinates yields this error:

```
Traceback (most recent call last):
  File "c:/Users/Federico/Documents/GitHub/BehaviourAnalysis/Analysis/anatomy/visualize.py", line 84, in <module>
    injection = connectedPoints(Points(pts2), radius=10, mode=2)
  File "C:\Users\Federico\AppData\Local\conda\conda\envs\behav\lib\site-packages\vtkplotter\analysis.py", line 1321, in connectedPoints
    cpf = vtk.vtkConnectedPointsFilter()
AttributeError: module 'vtk' has no attribute 'vtkConnectedPointsFilter'
```

Thanks for the help, 
Federico

**Comment by marcomusy** [comment]
I'm not sure if vtk8.2 has that filter, if not i think is for vtk8.9..

Possible alternatives i can think of are: `vtkplotter.cluster()`, `closestPoint(p, radius=r)`.

One other trick that comes to my mind is to use `mesh.clean(tol)` with some tolerance that imposes a minimum distance between points.. then compare the spatial distributions of cleaned vs uncleaned.
The sparse distribution is unaffected but any denser subsample is made sparse.

**Comment by FedeClaudi** [comment]
Hi, 

Yep I'm playing around with the different options that I've found around in the examples, thanks. 
I just stumbled upon this bug so I thought I'd let you know.
