### ISSUE TITLE
Visualizing displacements as deformed mesh

### ISSUE THREAD

**Issue by Rbravo555** [marcomusy/vtkplotter#104]
Good day,

I have the results from an structural simulation. The data on each point is a vector with 3 components. However, when loading it to VTKPLOTTER, the colors in the mesh correspond only to the x-displacement. 

I would like to see the deformed mesh corresponding to the vector on each point and the color should correspond to the module of the vector.

![Screenshot from 2020-02-05 10-37-48](https://user-images.githubusercontent.com/46027276/73830266-aa276900-4804-11ea-9ba2-2b444f979196.png)

Can I get it to look like this: how?
![Screenshot from 2020-02-05 10-49-30](https://user-images.githubusercontent.com/46027276/73830661-4fdad800-4805-11ea-8a30-808a944c9e7e.png)

Many thanks!

**Comment by marcomusy** [comment]
Try:
```python
import numpy as np
from vtkplotter import *

mesh = CubicGrid(spacing=(5,1,1)).pos(0,1,1).lw(.1)
# mesh = load('computing_domain_0_1.vtk').lw(.1)

newpts = mesh.points()

# let's make up some displacemts:
displs = newpts[:,0]/10
# in your case:
# displs = mesh.getPointArray("DISPLACEMENT")

# displace the mesh
newpts[:,2] += displs
mesh.points(newpts) # set the new points
# in your case just:
# mesh.points(newpts+displs)

mesh.pointColors(displs, cmap='jet').addScalarBar()

show(mesh, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/73834192-94697200-480b-11ea-9803-b08ad3c528a7.png)

**Comment by Rbravo555** [comment]
Thanks a lot. Following the recommendations the output is as expected.

![Screenshot from 2020-02-07 17-30-03](https://user-images.githubusercontent.com/46027276/74046948-cb888080-49cf-11ea-94fd-cbbbe70de768.png)
