### ISSUE TITLE
Alpha of Picture leads to (only) one sided transparency

### ISSUE THREAD

**Issue by m-albert** [marcomusy/vtkplotter#105]
Hi,

I was wondering about the following: A Picture with transparency (alpha value) is only transparent from one side. Is this unintended / a bug or does it somehow depend on the lighting or something in the scene? Sorry that I'm a bit confused.

Thanks!

```python
#from vtkplotter import Plotter, Text2D, datadir
from vtkplotter import Plotter, datadir

vp = Plotter(axes=3, verbose=0)

for i in range(5):
    p = vp.load(datadir+"images/dog.jpg") # returns Picture
    p.crop(bottom=0.2)             # crop 20%
    p.scale(1-i/10.0).alpha(0.8)   # picture can be scaled in size
    p.rotateX(20*i).pos(0,0,30*i)  # (can concatenate methods)

#vp += Text2D(__doc__)
vp.show()
```

**Comment by marcomusy** [comment]
Hi,

this is related to the difficulty of rendering multiple transparent objects.. Setting:
```python
from vtkplotter import settings
settings.useDepthPeeling = True
```
should fix the issue.

**Comment by m-albert** [comment]
Great, that fixed the issue.
Thanks a lot!
