### ISSUE TITLE
can't interact with show and mouse

### ISSUE THREAD

**Issue by cyrenaique** [marcomusy/vtkplotter#109]
Hello,
Very nice job, I am struggling with interacting with 3d window (on windows, python)
I tried : 
vp = Plotter(bg='black')
# show both Volume and Mesh
vp.show(vol1,vol2,interactive=0)
vp.interactor.Render()
vp.interactor.Start()

and onmy show with interactive=True but everytime I click in the window it's closing....
I guess I missed something
Best,
Arnaud

**Comment by marcomusy** [comment]
Hi Arnaud,
thanks for your interest, can you reproduce this minimal example:
```python
from vtkplotter import *

vol1 = load(datadir+'embryo.tif').scale(0.05)
vol2 = load(datadir+'embryo.slc')

show(vol1, vol2, bg='black', axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/76436120-225eec80-63b8-11ea-8eb8-baefefb176a8.png)

**Comment by cyrenaique** [comment]
Thanks for the quick answer,
I do see volumes but can not rotate or move anything, the window just close.
Best,

**Comment by marcomusy** [comment]
Is is only related to volumes or it's the same with meshes?
```python
from vtkplotter import *

vol1 = load(datadir+'embryo.tif').scale(0.05)
sph = Sphere()

show(vol1, sph)
```
Or, can you run this?
https://lorensen.github.io/VTKExamples/site/Python/GeometricObjects/Cone/

**Comment by cyrenaique** [comment]
the vtk runs and works well, trying to find embryo.tif now...

**Comment by cyrenaique** [comment]
ok I didn't install the examples, doing it now

**Comment by cyrenaique** [comment]
doesn' work with examples, same behaviour, the window closed as soon as I try to interact with it

**Comment by cyrenaique** [comment]
Sorry, I can't help u, I don't have any log or debug info, running on dell laptop, python 3.7 ,nvidia gtx1050 +intel gpu, vtk visualisation works and interact well, but show() renders but no interaction with mouse, keyboard ok for what I succeeded to test

**Comment by marcomusy** [comment]
OK, thanks for reporting this, I'll give it a try on a windows system to see if i can reproduce the issue!

**Comment by RubendeBruin** [comment]
Which VTK version are you using?

**Comment by marcomusy** [comment]
...also, what happens if you add:

```python.
# Allow to interact with scene during interactor.Start() execution
settings.allowInteraction = False
```

**Comment by RubendeBruin** [comment]
I can not reproduce the issue on Windows 10 with vtk 8.2.0

Some of the keys presses do cause the renderer to crash, but that is a known problem of vtk and has been solved on the master branch of vtk.

**Comment by cyrenaique** [comment]
settings.allowInteraction = False, doesn't change anything, I use vtk 8.1.0, I will try to update to vtk 8.2

**Comment by cyrenaique** [comment]
I have vtk 8.1.2 actually

**Comment by cyrenaique** [comment]
is it correct ?
![image](https://user-images.githubusercontent.com/1596752/76516203-48899880-645b-11ea-9ae7-d4bdc67fbd4f.png)
win32OpenGL?

**Comment by cyrenaique** [comment]
Also, in Scripts I have vtkplotter not vtkplotter.exe when I modify the name and run it:
This version of Anaconda3\Scripts\vtkplotter.exe is not compatible with the version of Windows you're running.
Compatibily mode doesn' change anything.
version installed : Successfully installed vtkplotter-2020.2.1
strange...

**Comment by marcomusy** [comment]
- On windows it looks like that the window title is ignored..

- you should not change vtkplotter to vtkplotter.exe because the file is a python script, you should rather run it with command `python vtkplotter`

Does this work for you?
```python
import vtk
from vtkplotter import load, datadir

vol = load(datadir+'embryo.tif')

ren = vtk.vtkRenderer()
ren.AddActor(vol)

renWin = vtk.vtkRenderWindow()
renWin.AddRenderer(ren)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)
iren.Initialize()
iren.Start()
```

**Comment by cyrenaique** [comment]
This one works well, my bad for vtkplotter, vtkplotter is working well also. only problem with show....

**Comment by marcomusy** [comment]
OK. Next step:
```python
from vtkplotter import load, datadir, Plotter

vol = load(datadir+'embryo.tif')

vp = Plotter()

ren = vp.renderer
iren = vp.interactor

ren.AddActor(vol)

iren.Initialize()
iren.Start()
```

**Comment by cyrenaique** [comment]
this one crash

**Comment by cyrenaique** [comment]
show(datadir+'embryo.tif'), this also crash

**Comment by marcomusy** [comment]
OK, but does it render an image? Any crashing message?

Next:
```python

import vtk
from vtkplotter import load, datadir, Plotter, settings

settings.allowInteraction=False # try both

vol = load(datadir+'embryo.tif')

vp = Plotter()

ren = vp.renderer
iren = vp.interactor
renWin = vp.window

ren.AddActor(vol)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(renWin)
iren.Initialize()
iren.Start()
```

**Comment by cyrenaique** [comment]
they all render images, no message, and this last one works (rendering, interact). when I say crash its for interaction

**Comment by cyrenaique** [comment]
True and False are working

**Comment by marcomusy** [comment]
next:
```python
import vtk
from vtkplotter import load, datadir, Plotter, settings, Sphere

settings.allowInteraction=False

sph = Sphere().lw(0.1)

vp = Plotter()

ren = vp.renderer
ren.AddActor(sph)

iren = vtk.vtkRenderWindowInteractor()
iren.SetRenderWindow(vp.window)

iren.AddObserver("LeftButtonPressEvent", vp._mouseleft)
iren.AddObserver("RightButtonPressEvent", vp._mouseright)
iren.AddObserver("MiddleButtonPressEvent", vp._mousemiddle)
iren.AddObserver("KeyPressEvent", vp._keypress)

vsty = vtk.vtkInteractorStyleTrackballCamera()
iren.SetInteractorStyle(vsty)
iren.Initialize()
iren.Start()
```
try interact, press `h`

**Comment by cyrenaique** [comment]
works, h gives the help

**Comment by cyrenaique** [comment]
STOP!! import vtk
from vtkplotter import load, datadir, Plotter, settings, Sphere,show

settings.allowInteraction=False

sph = Sphere().lw(0.1)
show(sph)

this works....

**Comment by marcomusy** [comment]
..and the Volume can also be visualized and interacted with?

**Comment by cyrenaique** [comment]
Yes, but any datadir volume crash...:
from vtkplotter import  load, datadir, settings, Sphere,show

settings.allowInteraction=True
vol1 = load(datadir+'embryo.tif').scale(0.05)
# sph = Sphere().lw(0.1)
show(vol1)

crash, sphere is working well

**Comment by cyrenaique** [comment]
True or False doesn't change anything

**Comment by marcomusy** [comment]
Ok, this points to a gpu problem, the `show()` seems unrelated. 
Try
```python
from vtkplotter import datadir, settings, Sphere, Volume, show
from vtkplotter.vtkio import loadImageData

settings.allowInteraction=True

img = loadImageData(datadir+'embryo.tif') # loads a vtkImageData obj

# mapper types are: gpu, opengl_gpu, smart, fixed, tetra, unstr
vol = Volume(img, mapperType='smart') 

show(vol)
```

**Comment by cyrenaique** [comment]
crash, I am not sure which gpu card I am using with python, with vtk sure it uses the nvidia geforce, maybe show uses the intel for any reasons

**Comment by cyrenaique** [comment]
I was right, I force python to use geforce and it works now... so sorry for these troubles:
![image](https://user-images.githubusercontent.com/1596752/76530512-1cc6dc80-6474-11ea-8440-ebbde898eecd.png)

**Comment by cyrenaique** [comment]
And huge thanks to you for your help, hope it can help others

**Comment by cyrenaique** [comment]
Fixed in less than 24h :)
23h33minutes

**Comment by marcomusy** [comment]
Indeed it should not crash with 'smart' mapper type... anyway,
thanks for your patience in testing and debugging the issue

**Comment by cyrenaique** [comment]
well, that was in my interest :)
