### ISSUE TITLE
computing centroid of faces

### ISSUE THREAD

**Issue by ifermion** [marcomusy/vtkplotter#112]
Hi,

I'm wondering what the most straightforward way to compute the centroid of a mesh face is. Is there any built-in function ?
What I'm doing now is using `mesh.faces()`, `mesh.points()` to get the faces and points and then iterate over the 3 points that connect the face to get its centroid coordinates.

Any idea ?

Thanks in advance !

**Comment by marcomusy** [comment]
Hi, Yes - you can use `mesh.cellCenters()`. See examples in 
`basic/delaunay2d.py`
`basic/mesh_coloring.py`

**Comment by ifermion** [comment]
got it, thanks for the fast reply.
