### ISSUE TITLE
scale bar title text formatting

### ISSUE THREAD

**Issue by ifermion** [marcomusy/vtkplotter#123]
Hi again,

I've got a quick question this time on formatting the scalabar title text. I know that there is titleFontSize argument, but it seems to only modify the font size of the scale as you can see in the attachment. Any idea as to what I might be missing and how I could change the font size of the title text and may be make it bold ?

Thank you again for this wonderful library !

`from vtkplotter import Sphere`

`s = Sphere().addElevationScalars(lowPoint=(0,0,0), highPoint=(1,1,1))`
`s.addScalarBar(title='Test Title',titleFontSize=30).show(axes=1)`

![screenshot](https://user-images.githubusercontent.com/24443359/78982432-67468200-7b22-11ea-9b4c-a4c12f4713c9.png)

**Comment by marcomusy** [comment]
thanks for spotting the bug :) it will be fixed in the next release.
meanwhile you can use this hack:
```python
from vtkplotter import *

s = Sphere().addElevationScalars(lowPoint=(0,0,0), highPoint=(1,1,1))
s.addScalarBar(title='Test Title', titleFontSize=15)

vp = show(s, axes=1, interactive=False)
vp.scalarbars[0].GetTitleTextProperty().SetFontSize(20)
show(interactive=True)
```

**Comment by ifermion** [comment]
Thanks a lot for the hack ! didn't know it was a bug though !

All the best !!
