### ISSUE TITLE
Phong shading/normal computation doesn't seem to work, unless model is loaded from a file with normal information

### ISSUE THREAD

**Issue by MichaelRabinovich** [marcomusy/vtkplotter#124]
It seems that if I load an OBJ model with specified normals in the file than the following line seems to render it correctly:
mesh_t = vp.load("mesh_with_vn.obj").phong()
But if it doesn't have normals, than the following line doesn't
mesh_t = vp.load("mesh_without_vn.obj").computeNormals().phong()
and in fact shows flat shading.

I've tried to look for explanations and also set "settings.computeNormals = True", but nothing seems to work. Am I doing something wrong?

**Comment by marcomusy** [comment]
Hi, can you reproduce this:
```python
from vtkplotter import datadir, load

load(datadir+"shuttle.obj").show() # shuttle.obj has no normals
```
![image](https://user-images.githubusercontent.com/32848391/79161161-4a88a380-7ddb-11ea-9311-6bde86e25efd.png)

versus:
```python
load(datadir+"shuttle.obj").computeNormals().phong().show()
```
![image](https://user-images.githubusercontent.com/32848391/79161200-5b391980-7ddb-11ea-80f6-c3cae902b670.png)

**Comment by MichaelRabinovich** [comment]
Thanks for the quick answer! It does work with your mesh, but it doesn't work with the following obj that I'm attaching here:

https://www.dropbox.com/sh/xiljwiq9l0y467h/AAAS-pmYQ5yqBGLvPWWe8Ne5a?dl=0

That's kinda weird. Any idea why?

**Comment by marcomusy** [comment]
looks like your mesh has lots of coincident points!
`clean()` reduce them from 30k to 5k
```python
from vtkplotter import load
load("mesh.obj").printInfo().clean().printInfo().computeNormals().phong().show()
```
![image](https://user-images.githubusercontent.com/32848391/79242674-e6b2b900-7e74-11ea-960d-e551ddc66dad.png)

**Comment by MichaelRabinovich** [comment]
Thanks it does work, but I'm still a bit confused. The obj file has only 5,023 vertices. This is what I see when I open it in meshlab, as well as when looking at the raw textual data in a text editor.
The raw textual data definitely has 5,023 vertices lines, and doesn't even have 30K lines/entries for the entire vertices, uv coordinates and faces.

Why does it think it has so many points and/or duplicates?

**Comment by marcomusy** [comment]
You're right! It quite puzzling, though unrelated to vtkplotter because the vtkOBJReader class already generates all these coincident points... my guess is that it is related to the presence of 3 texture files in the mtl file (?)
```python
import vtk
r = vtk.vtkOBJReader()
r.SetFileName("/home/musy/downloads/mesh.obj")
r.Update()
print(r.GetOutput())
```
`Number Of Points: 29928`

**Comment by MichaelRabinovich** [comment]
Deleting the mtl altogether still keep it with 29K vertices. Anyhow I guess it's a bug in vtkOBJReader. As long as clean() fix that, I'm happy.
Thanks for the help.
