### ISSUE TITLE
update dolfinx tests to dolfinx

### ISSUE THREAD

**Issue by RizzerOnGitHub** [marcomusy/vtkplotter#125]
The dolfinx tests in vtkplotter import dolfin, which is the alpha-release API for dolfinx.  The beta release has updated the namespace to dolfinx so that old dolfin and dolfinx can be installed at the same time.

So the dolfinx tests need to be updated to import dolfinx instead of dolfin.

**Comment by marcomusy** [comment]
Thanks Drew for letting me know, i made the changes though at the minute dolfinx support is not  ready and the tests in dolfinx folder are not yet run.
