### ISSUE TITLE
Displaying multiple volume objects

### ISSUE THREAD

**Issue by cerr** [marcomusy/vtkplotter#126]
Thanks for this nice library. I am running into an issue while displaying multiple volumes. I am trying to superimpose CT scan and radiation dose distribution using the following code sample. I get the following warning and only one Volume object is rendered in jupyter notebook.

Warning: multirendering is not supported in jupyter.

````
import numpy as np
from vtkplotter import *
settings.useDepthPeeling = False
settings.embedWindow(backend='itk')
scanArray = 1000*np.random.randn(20, 20, 20)
doseArray = 100*np.random.randn(15, 15, 15)
scan = Volume(scanArray)
dose = Volume(doseArray)
vp = Plotter(shape=(2,1))
vp.show(scan,at=0,axes=1)
vp.show(dose,at=1)
````

However, the following example works even though it shows the same warning:
````
from vtkplotter import *
vp = Plotter(shape=(3,1))
s = Sphere()
c = Cube()
p = Paraboloid()
vp.show(s, at=0)
vp.show(p, at=1)
vp.show(c, at=2, interactive=True)
````

**Comment by marcomusy** [comment]
Thanks @cerr for your interest, unfortunately jupyter support comes with a number of limitations, one of these is rendering on independent subwindows, and also only one volume can be rendered in the scene.
One option is to allow a separate window to pop up from the jupyter session by setting
`embedWindow(False)`
then one can also display volumes in the same window by setting their position, e.g.
```python
import numpy as np
from vtkplotter import *
#settings.useDepthPeeling = False
#settings.embedWindow(backend='itk')
scanArray = 1000*np.random.randn(20, 20, 20)
doseArray = 100 *np.random.randn(15, 15, 15)
scan = Volume(scanArray)
dose = Volume(doseArray).x(30)

show(scan, dose, axes=1)
```
![image](https://user-images.githubusercontent.com/32848391/79400185-c9b9db00-7f85-11ea-8cb6-4717cdb6bc96.png)

**Comment by cerr** [comment]
Thanks!
