### ISSUE TITLE
AlignICP is not found

### ISSUE THREAD

**Issue by unidesigner** [marcomusy/vtkplotter#14]
https://github.com/marcomusy/vtkplotter/blob/fddd3c3fd1178e6d1fbf3c597033cfad81d4dec2/examples/basic/align2.py#L26

**Comment by marcomusy** [comment]
uhm that's strange are you sure you are running the latest version?
`pip install --upgrade vtkplotter`

i'm getting the expected result from the script:
![image](https://user-images.githubusercontent.com/32848391/55072651-f1dd5000-508b-11e9-9853-01e6cbd06d02.png)

**Comment by unidesigner** [comment]
Sorry, again an outdated version was picked up first. Now everything works. Nice example!
