### ISSUE TITLE
Volume problems

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vtkplotter#141]
Hi Marco, sorry to be opening so many issues...

I was playing around with the `Volume` class and found a couple small issues. 

### Threshold in range
There seems to be something weird with `volume.threshold`, if I only pass `vmin` or `vmax` it works as expected, but if I pass both it just returns the full volume and which particular values I use doesn't change anything (in fact I can even pass `vmax > vmin`). 

### bug in volume.resample
```
  File "/Users/federicoclaudi/Documents/Github/BrainRender/workspace.py", line 41, in <module>
    vol.resample([.1, .1, .1])
  File "/Users/federicoclaudi/miniconda3/envs/brainrender/lib/python3.7/site-packages/vtkplotter/volume.py", line 291, in resample
    oldsp = self.GetSpacing()
AttributeError: 'Volume' object has no attribute 'GetSpacing'
```

### setting volume transparency.
I have these volumes that are 0 in empty voxels and >0 where there's something. The actual scalar value in non-empty voxels doesn't matter, it's just to label voxels belonging to different structures. 
So when rendering the volume I wanted all the 0 voxels to have `alpha=0` and all the non-zero voxels to have `alpha=1`, but I couldn't find an easy way to do that with the `alpha` argument of `Volume`. I ended up doing this which works fine:

```
    otf = vol.GetProperty().GetScalarOpacity()
    otf.RemoveAllPoints()
    otf.AddPoint(vmin, 0) # set to transparent
    otf.AddPoint(vmin+.1, alpha) # set to opaque
    otf.AddPoint(data.max(), alpha)
```

but I thought perhaps you wanted to build this possibility into the `Volume` class. 

All the best, 
Fede

P.s.: The slicers in the latest release look awesome!

**Comment by marcomusy** [comment]
Hi Federico
Thanks for reporting these issues!
- I fixed the first bug,
- second one I rewrote the threshold api as:
```python
    def threshold(self, above=None, below=None, replaceWith=0):
        """
        Binary or continuous volume thresholding.
        Find the voxels that contain a value above/below the input values
        and replace them with a new value (default is 0).
        """
        th = vtk.vtkImageThreshold()
        th.SetInputData(self.imagedata())
        
        if above is not None and below is not None:
            if above<below:
                th.ThresholdBetween(above, below)
                th.SetInValue(replaceWith)
            elif above==below:
                return self
            else:
                th.SetReplaceOut(True)
                th.SetOutValue(replaceWith)
                th.ThresholdBetween(below, above)
                
        elif above is not None:
            th.ThresholdByUpper(above)
            th.SetInValue(replaceWith)

        elif below is not None:
            th.ThresholdByLower(below)
            th.SetInValue(replaceWith)

        th.Update()
        return self._update(th.GetOutput())
```
and tested it with example: 
`vtkplotter -ir interpolateVolume`
(you can search and run any of the examples this way)
- about the transparency: what if you do
```python
vol.threshold(above=0.0001, replaceWith=1).alpha([0,1])
```
..maybe it's not very intuitive..

> P.s.: The slicers in the latest release look awesome!

thanks!
Marco

**Comment by FedeClaudi** [comment]
Hi, 

Thanks for getting back to me so quickly and fixing the bugs, the tresholding works correctly now. 

For the transparency, this:
```
vol.threshold(above=0.0001, replaceWith=1).alpha([0,1])
```
won't do because I still want to keep the actual values in the original volume to be the value they are. The code above looses all the information in the value of the voxels that are >0, which is important for my application. 

That's why I ended up using this solution instead:
```
    otf = vol.GetProperty().GetScalarOpacity()
    otf.RemoveAllPoints()
    otf.AddPoint(vmin, 0) # set to transparent
    otf.AddPoint(vmin+.1, alpha) # set to opaque
    otf.AddPoint(data.max(), alpha)
```
as this doesn't alter voxel values, just hides the 0 voxels. 

Thanks, 
Fede

**Comment by marcomusy** [comment]
I see it's a good point - I could actually implement it as passing to `alpha()` a tuple like:
`volume.alpha([(val1,alpha1), (val2,alpha2), ...])`
which in your case would read:
`volume.alpha([(0,0), (0.1,1), (data.max(),1))`

without disrupting the current default syntax.

**Comment by FedeClaudi** [comment]
yep I think that would work, awesome thanks!

**Comment by marcomusy** [comment]
In the latest push this should be possible check:
`vtkplotter -ir interpolateVolume`

line:
`# vol.alpha([(0.3,0.3), (0.9,0.9)]) # alternative way, by specifying (xscalar, alpha)`
