### ISSUE TITLE
Saving actor to .obj

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vtkplotter#142]
Sorry again Marco, I'm having problems saving meshes to `.obj`. 

I've created a mesh with `volume.isosurface` and saved it as either `.obj` or `.vtk`, then just loaded the files and rendered:

```
obj = load('test.obj').c('red')
vtk = load('test.vtk').x(500).c('green')

show(obj, vtk)
```
The result is this:

<img width="618" alt="image" src="https://user-images.githubusercontent.com/17436313/81111924-bf9c5400-8f15-11ea-804a-43da1d967707.png">

Any idea about what could be going wrong?

**Comment by marcomusy** [comment]
Try with 
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
this gives me:
```python
from vtkplotter import *

m = load(datadir+'man_low.vtk').c('green').lw(1)#.triangulate()

m.write("man_low.obj")

obj = load('man_low.obj').c('red').x(2).lw(1)

show(m, obj, axes=1)
```
![Screenshot from 2020-05-06 00-28-50](https://user-images.githubusercontent.com/32848391/81122665-a4d7d880-8f31-11ea-84c3-50440bb3c560.png)

**Comment by FedeClaudi** [comment]
Hi, 

It works perfectly fine in the example code above, but it still fails in the same manner with my mesh.

Looking at the content of the objs files:

<img width="839" alt="image" src="https://user-images.githubusercontent.com/17436313/81123728-b1f1c900-8f2b-11ea-9606-61752eaff16b.png">

it looks like a point is added repeatedly to test obj I create from my mesh, but not with the one from your example.

**Comment by marcomusy** [comment]
that's strange! you can maybe provide the source mesh?

**Comment by FedeClaudi** [comment]
Okay, the .obj file is quite large so I had to upload them somwehere, let me know if you can get them from here: https://drive.google.com/open?id=1khhZbPeHXBZfmR0RrefPnwjX4Q6YyZtd

**Comment by marcomusy** [comment]
..it was a bit painful but i could eventually find the bug..
i just ushed a version with the fix.
Note that the obj does not store scalars, only the mesh.

ps: the points in your dump are not added repeatedly... they 're just in the same yz plane.. i got confused by that to...

**Comment by FedeClaudi** [comment]
hi marco sorry, I've updated vtkplotter but I'm getting the same output, am I missing something?

**Comment by FedeClaudi** [comment]
hey sorry for the deleted comment, as you pointed out in https://github.com/marcomusy/vtkplotter/issues/120 I hadn't correctly updated from the master. 

It now works perfectly, thank you so much!
