### ISSUE TITLE
surfaceIntersection problem and keypress question

### ISSUE THREAD

**Issue by jsanchez679** [marcomusy/vtkplotter#143]
Hi @marcomusy 
It's me again! I have been using vtkplotter a lot recently and it amazes me the amount of things one can do with it! Thanks for developing it!
This time I have two questions. The first one is related to using the function surfaceIntersection. I ran the example and it works fine, but I then changed the tube and put a cube instead, and I got no intersecting contours, even though the car and the cube where clearly intersecting.... I tried putting cubegrid instead, since that mesh could have more vertices than a simple cube, but again no intersecting contours... the error I got, which by the way made me restart the kernel is next: 
![Capture2](https://user-images.githubusercontent.com/10684503/81162468-23aa3100-8f85-11ea-9667-cd810edd922d.PNG)

I am interested in using this function to get the intersection of one of the meshes I have been processing using vtk with a cube/cubegrid (any will work) and was wondering if you have any idea why it is not working with the car example... I tried it with my mesh as well and didn't work either...

The second question I have is related the keypress.py script, where you define the function myfnc to create spheres in the positions you click and print the coordinates of those clicks. I was wondering if there is a way I can add the positions of the coordinates inside a list apart or instead of just printing them. I have tried changing the function, but did't know then how to recall the return as there is a particular way you call the function to be used inside the plotter....

```
def myfnc(key):
    sel_pts = []
    mesh = vp.clickedActor
    if not mesh or key != "c":
        printc("click a mesh and press c.", c="r")
        return
    #printc("clicked mesh    :", mesh.filename[-40:], c=4)
    printc("clicked 3D point:", mesh.picked3d, c=4)
    #printc("clicked renderer:", [vp.renderer], c=2)

    vp.add(Sphere(pos=mesh.picked3d, r=5, c="v"))
    
    sel_pts.append(mesh.picked3d)

    return sel_pts

vp.keyPressFunction = myfnc 
```

Thanks again in advance for all you previous replies. 
best wishes, 
Juliana

**Comment by marcomusy** [comment]
> Hi @marcomusy
> It's me again! I have been using vtkplotter a lot recently and it amazes me the amount of things one can do with it! Thanks for developing it!

Thanks! 

> This time I have two questions. The first one is related to using the function surfaceIntersection. I ran the example and it works fine, but I then changed the tube and put a cube instead, and I got no intersecting contours, even though the car and the cube where clearly intersecting.... I tried putting cubegrid instead, since that mesh could have more vertices than a simple cube, but again no intersecting contours... the error I got, which by the way made me restart the kernel is next

are you sure you are not forgetting the `triangulate()`? This works for me:
```python
from vtkplotter import *

car = load(datadir+"porsche.ply").alpha(0.2)

cb = Cube(side=8).triangulate().color("violet").alpha(0.2)

contour = surfaceIntersection(car, cb).lw(4)

show(car, cb, contour)
```
![image](https://user-images.githubusercontent.com/32848391/81194449-f37e8480-8fbc-11ea-91cc-14034855817a.png)

 
> I am interested in using this function to get the intersection of one of the meshes I have been processing using vtk with a cube/cubegrid (any will work) and was wondering if you have any idea why it is not working with the car example... I tried it with my mesh as well and didn't work either...
> 
> The second question I have is related the keypress.py script, where you define the function myfnc to create spheres in the positions you click and print the coordinates of those clicks. I was wondering if there is a way I can add the positions of the coordinates inside a list apart or instead of just printing them. I have tried changing the function, but did't know then how to recall the return as there is a particular way you call the function to be used inside the plotter....

I would simply define a list outside the function scope (you don't need the `global` keyword in this case...):
```python
from vtkplotter import *

mylist = []

def myfnc(key):
    mesh = plt.clickedActor
    if not mesh or key != "c":
        printc("click a mesh and press c.", c="r")
        return
    printc("clicked mesh    :", mesh.name, c=4)
    printc("clicked 3D point:", mesh.picked3d, c=4)

    plt.add(Sphere(pos=mesh.picked3d, r=0.1, c="b"))
    mylist.append(mesh.picked3d)

plt = Plotter()
car = load(datadir+"porsche.ply").alpha(0.2)
car.name = "Porsche"

cb = Cube(side=8).triangulate().color("violet").alpha(0.2)
plt.keyPressFunction = myfnc  # make it known to Plotter class
printc("\nPress c to execute myfnc()", c=1)

show(car, cb)

printc('all clicked coords:', mylist)
```

**Comment by jsanchez679** [comment]
Hi Marco! 
Every thing worked fine with your suggestions. 
Many thanks
