### ISSUE TITLE
How to convert vtk polydata to data image and save as vtk file

### ISSUE THREAD

**Issue by wangyibin0011** [marcomusy/vtkplotter#145]
As the title

**Comment by marcomusy** [comment]
There are different possibilities depending on what you're looking for, e.g.:
```python
from vtkplotter import *

s = ParametricShape(1).pointColors(cmap='jet')
s.addScalarBar().printInfo()
# print(s.polydata()) # vtkPolyData

vol1 = interpolateToVolume(s, dims=(20,20,20), radius=0)
vol2 = volumeFromMesh(s)
# print(vol2.imagedata()) # vtkImageData
write(vol2, 'vol.vti')

show(s, vol1, vol2, N=3)
```
![image](https://user-images.githubusercontent.com/32848391/81562157-a1f74080-9394-11ea-8615-20be4ef6a626.png)

Then:
`vtkplotter vol.vti`
![image](https://user-images.githubusercontent.com/32848391/81561919-44fb8a80-9394-11ea-9c4e-102509a9b513.png)

**Comment by wangyibin0011** [comment]
Thank you very much!
