### ISSUE TITLE
Assigning names to volume objects in k3d controls window

### ISSUE THREAD

**Issue by anorak94** [marcomusy/vtkplotter#149]
Hey is there a way to label the volume objects in the k3d window instead of having Volume #1 #2 etc.

Thanks

**Comment by marcomusy** [comment]
Yes, try set a name with:
`vol.name = 'sometext'`

**Comment by anorak94** [comment]
yeah i do that but it doestn work 

```
vol_i = Volume(vol_arr, shape=self.vol_arr.shape, mode=0)
vol_i = vol_i.alpha(0.4)
vol_i = vol_i.c("red")
vol_i.name = struct
```

<img width="2048" alt="Screenshot 2020-05-18 at 01 59 15" src="https://user-images.githubusercontent.com/45297533/82212940-a7640600-9913-11ea-8da6-dd122cce786c.png">
