### ISSUE TITLE
Jupyter plot close.

### ISSUE THREAD

**Issue by calugo** [marcomusy/vtkplotter#20]
Hello!

Ok, first of all, congrats! this is a great effort! 

Second, Ok, I normally work with fenics running on docker containers and often use jupyter notebooks as interface. I am not a docker expert and despite being able to install vtkplotter in my containers its proven to be quite tricky to get it to work with jupyter in a container. So leaving this on the side for a second . I then installed fenics using anaconda, which at the minute its tha same release as my docker images   2018.1.0, which its great as I am more competent managing conda environments.  which makes vtkplotter also straigthforward to install via pip. Up to here all its great

I started to play with notebooks again (as cli and scripts all work fine) and yes, at least in the most elementary cases the plotter works.  (all this is under ubuntu 18)

![vtkjupyter](https://user-images.githubusercontent.com/6739276/57015737-46856500-6c0e-11e9-845b-659266a2304e.png)

However, as expected the new window does not close until it is killed, and the plotter of course becomes not usable (a new call kills the kernel). So my question is, is there a standard way in which the vtk windows should be handled (closed)? The snippet i use to create the pic above is:

`from vtkplotter.dolfin import datadir, plot

mesh = dolfin.Mesh(datadir+"dolfin_fine.xml")

pme=plot(mesh)
`   
I really would appreaciate any help with this.

Thanks a lot and again, great module!

Regards 

Carlos

**Comment by marcomusy** [comment]
@calugo 
Hi Carlos! Thanks a lot for your interest and this great feedback!!
To be perfectly honest I'm not expert of jupiter (shame on me..) but you are absolutely right: this not handled properly, if someone wants to type-in commands in a python or jupiter session.
I could easily add a small function that closes the window.
Meanwhile this should work (python3):
```python
import dolfin
from vtkplotter.dolfin import datadir, plot, Plotter

def closeWindow(pme=None):
	if not pme:
		from vtkplotter.settings import plotter_instance
		pme  = plotter_instance
		if not pme:
			return
	pme.window.Finalize()
	pme.interactor.TerminateApp()
	del pme.window
	del pme.interactor
	return pme

mesh = dolfin.Mesh(datadir+"dolfin_fine.xml")

pme = plot(mesh)
 
# now I press 'q' to exit the window interaction, 
# windows stays open but not reactive anymore

input('Control returns to terminal shell (press Enter)')

closeWindow()

# window should now close, the Plotter instance becomes invalid
# but mesh object still exist in it:

print(pme)
#pme.show() #this would cause error

# can create a brand new Plotter and show the old object
pme2 = Plotter(title='Second Plotter instance')
pme2.show(pme.actors[0].color('green'))
```

On the other hand one can go back to interaction by simply call
```python 
#.... non interactive script
plot()
```

Let me know if this works for you!
Cheers
Marco

**Comment by calugo** [comment]
Hi!
Thanks for the reply! This solutions works like a charm. 
Carlos.

**Comment by marcomusy** [comment]
@calugo 
fantastic, I will add the new function in the next release.
I'm also thinking of adding the method `interactive()` to go back to the rendering window, which would be equivalent to `plot()` with no arguments... maybe that's more intuitive... (?)
M.

**Comment by calugo** [comment]
Hi, well i think that this would be useful as often one likes to work along the image.

I think you commited the above function? Thanks  a lot.

**Comment by marcomusy** [comment]
yes - it should be already available in the release,
cheers
marco
