### ISSUE TITLE
close window when using vtkplotter from jupyter notebook

### ISSUE THREAD

**Issue by siegLoesch** [marcomusy/vtkplotter#23]
Thank you for vtkplotter!
I am unable to clear or close the vtkplotter window after plotting by hitting the top right cross. Key strokes 'q' and 'e' deactivate the window but do not close it. Key stroke 'esc' yields to died jupyter kernel that restarts automatically afterwards followed by the following messages:

_ERROR:root:Invalid alias: The name clear can't be aliased because it is another magic command.
ERROR:root:Invalid alias: The name more can't be aliased because it is another magic command.
ERROR:root:Invalid alias: The name less can't be aliased because it is another magic command.
ERROR:root:Invalid alias: The name man can't be aliased because it is another magic command._

I did several demos but above described behavior is always the same. I tried backends 'tk' and 'qt' with same result.
_System: debian 10 (buster)
The version of the notebook server is: 5.7.8
Python 3.7.3rc1 (default, Mar 13 2019, 11:01:15) [GCC 8.3.0]
IPython 7.5.0
vtkplotter 2019.1.6, vtk 8.1.2, python 3.7_

The only workaround I found for the moment is to restart the jupyter kernel (what closes also all open vtkplotter windows).
I am wondering for the moment if the error comes from vtkplotter, jupyter or system. Please let me know if you experience similar behavior or found a solution. I attach my jupyter file:

[DolfinMeshExample.zip](https://github.com/marcomusy/vtkplotter/files/3149228/DolfinMeshExample.zip)

Best regards
Siegfried

**Comment by marcomusy** [comment]
Hi Sigfried
I just committed a version where you can do:
```python
from vtkplotter.dolfin import closeWindow

#...
plot(mesh)
closeWindow()
```

let me know if you encounter any problem with it!
Cheers
Marco

**Comment by marcomusy** [comment]
PS; remember you can go back to window interaction by calling
`plot() # w/ no arguments`

**Comment by siegLoesch** [comment]
Hello Marco,
your function _closeWindow()_ does the job. I tested it according your code stated what yields:
1) pressing button '_q_': closes the window
2) pressing button '_e_': closes the window

Pressing the '_esc_' button still results in a jupyter kernel crash with message: _The kernel appears to have died. It will restart automatically._ together with the error messages indicated before. That will not hinder me proceed working with vtkplotter much more intensively now! (What means also reading docs).
Great tool - thank you so much!
Siegfried

**Comment by marcomusy** [comment]
Thank you for your input!
Indeed you made me realize that the `esc` thing is not really good for jupiter users and actually redundant, so I will fix it in the next release..
All this is still a bit work in progress so If you feel there is any functionality missing/broken or that you would like to have dont hesitate to ask..
Cheers
Marco
