### ISSUE TITLE
Bug in examples/advanced/thinplate_grid.py?

### ISSUE THREAD

**Issue by Gjacquenot** [marcomusy/vtkplotter#24]
When running `thinplate_grid.py`, I have the following error. @marcomusy , could you have a look?

    Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
    IPython 7.4.0 -- An enhanced Interactive Python. Type '?' for help.

    from vtkplotter import *
    import numpy as np

    np.random.seed(2)

    grids = []
    for i in range(10):
        grids.append(Grid([0, 0, i / 10.0], resx=100, resy=100))
    act = mergeActors(grids)  # merge grids into a single object

    idxs = np.random.randint(0, act.N(), 10)  # pick 10 indexes

    ptsource, pttarget = [], []
    for i in idxs:
        ptold = act.getPoint(i) + np.random.randn(3) * 0.02
        ptsource.append(ptold)
        ptnew = ptold + [0, 0, np.random.randn(1) * 0.10]  # move in z
        pttarget.append(ptnew)

    warped = thinPlateSpline(act, ptsource, pttarget)
    warped.alpha(0.2).color("b")
    # print(warped.getTransform())

    apts = Points(ptsource, r=5, c="r")
    arrs = Arrows(ptsource, pttarget)

    show(warped, apts, arrs, Text(__doc__), axes=9, viewup="z", bg="w")

    ## -- End pasted text --
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-1-369e5917c20a> in <module>
        23 
        24 apts = Points(ptsource, r=5, c="r")
    ---> 25 arrs = Arrows(ptsource, pttarget)
        26 
        27 show(warped, apts, arrs, Text(__doc__), axes=9, viewup="z", bg="w")

    /usr/local/lib/python3.7/site-packages/vtkplotter/shapes.py in Arrows(startPoints, endPoints, s, scale, c, alpha, res)
        584     arrg = Glyph(pts, arr.GetOutput(),
        585                  orientationArray=orients, scaleByVectorSize=True,
    --> 586                  c=c, alpha=alpha)
        587     settings.collectable_actors.append(arrg)
        588     return arrg

    /usr/local/lib/python3.7/site-packages/vtkplotter/shapes.py in Glyph(actor, glyphObj, orientationArray, scaleByVectorSize, c, alpha)
        192     gly.SetColorModeToColorByScalar()
        193 
    --> 194     if orientationArray != "":
        195         gly.OrientOn()
        196         gly.SetScaleFactor(1)

    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by marcomusy** [comment]
@Gjacquenot 
I just committed a new version, can you check if you still get the error?

PS: I've also changed a bit the basic/mesh_modify.py example is case you need it..

**Comment by Gjacquenot** [comment]
Unfortunately, I got the same error. Thanks for the update of basic/mesh_modify.py!

**Comment by marcomusy** [comment]
i guess it's python 3.7 which is more strict on the != operator.. i've made a fix to commit asap.

**Comment by marcomusy** [comment]
..is the error still there?

**Comment by Gjacquenot** [comment]
Hi @marcomusy , I have tested version 3.0, and it works like a charm! Thanks for the patch!
