### ISSUE TITLE
calculate the inner volume of an object?

### ISSUE THREAD

**Issue by henryliangt** [marcomusy/vtkplotter#26]
Hi, Marco Musy,
How are you doing there ?

I am new using vtkplotter, trying to calculate the inner volume of my .stl files. 
didn't see a ready use method yet. 
Is there one ready developed by you ?

tks.

Henry

**Comment by marcomusy** [comment]
@henryliangt 
Hi Henry you should be able to get it this way, Eg.:
```python
from vtkplotter import *

#c = Cube(side=2).triangle() # make triangular mesh
c = load(datadir+'shuttle.stl').scale(10)

print('volume is:', c.volume())

c.show(axes=1)
````
![image](https://user-images.githubusercontent.com/32848391/58419670-84e63680-808b-11e9-9350-367b76dfabc9.png)

this is implemented natively in VTK:
https://vtk.org/doc/nightly/html/classvtkMassProperties.html
