### ISSUE TITLE
Projection type

### ISSUE THREAD

**Issue by siegLoesch** [marcomusy/vtkplotter#27]
Hello Marco,

reading the **vtkplotter** documentation I found:
_parallelScale (float),
    scaling used for a parallel projection ..._
and was wondering how to switch from perspective to parallel projection? For the moment I just get the perspective projection.

Best regards
Siegfried

**Comment by marcomusy** [comment]
@siegLoesch 
Hi Siegfried!
you just need to set the flag:
```python 
plot(u, infinity=True) # point of view is set at infinity
```
I agree that the naming is not the best..
Hope that helps
M.

**Comment by siegLoesch** [comment]
Hello Marco,
that works perfectly fine. Maybe the naming isn't that good - but your package and your support!
Thank you!
Siegfried

**Comment by marcomusy** [comment]
Update: in the latest release you need to 
```python 
from vtkplotter import plot, settings

settings.useParallelProjection = True

plot(...)
```
M.
