### ISSUE TITLE
no effect setting infinity with k3d

### ISSUE THREAD

**Issue by siegLoesch** [marcomusy/vtkplotter#29]
Hi Marco,
Am I wrong saying that embedding the plot into _jupyter notebook cell output_ and setting _infinity_ **True** or **False** has no effect and shows never a parallel projection?

Backend _panel_ is always in parallel projection mode but does not show axes and cmap.
I was playing around with example markmesh.
[markmesh.zip](https://github.com/marcomusy/vtkplotter/files/3293967/markmesh.zip)

Siegfried

**Comment by marcomusy** [comment]
@siegLoesch 
Hi Siegfried, you are right, for both k3d and panel only a subset of the rendering functionality is available at the minute.
Panel is horribly slow at start and doesn't like axes, k3d likes them too much the way they are and cannot be customized :)
Parallel projection is also fixed to my understanding, as you noticed.
K3D looks a great project and is rapidly evolving so in the future some missing functionality may be integrated in vtkplotter!
Marco

ps: k3d camera postion can be accessed after rendering with e.g.
```python

model_matrix = (
     1.0,  0.0, 0.0, 0.0,
     0.0,  0.0, 1.0, 0.0,
     0.0,  1.0, 0.0, 0.0,
     0.0,  0.0, 0.0, 1.0
)
plot = k3d.plot()
plot.camera = model_matrix
#and
#plot.reset_camera()
```

**Comment by siegLoesch** [comment]
Thank you Marco!
