### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by sariths** [marcomusy/vtkPlotter#3]
Hi @marcomusy , are there any other dependencies besides VTK to get the scripts up and running?
(Great project by the way!)

**Comment by marcomusy** [comment]
Hi @sariths 
thanks for your interest, the only dependency is numpy.
A couple of examples are using other packages like shtools (spherical harmonics expansion) or scipy.
If you have any other question do not hesitate to ask,
Cheers
Marco

**Comment by sariths** [comment]
@marcomusy that did it. Thanks!
