### ISSUE TITLE
vtkplotter - dolfin - mpi

### ISSUE THREAD

**Issue by siegLoesch** [marcomusy/vtkplotter#36]
Hello Marco,
I am expensively using _dolfin_ and therefore like _vtkplotter_ for "inSitu" display of simulation results. Everything works well as long as I start the python script with mpi support (For example: **mpiexec -np 4 navier-Stokes-lshape.py**).  In the later case 4 _vtkplotter_ windows open showing the results for each _dolfin mesh partition_.
Kindly ask you if there is any functionality within _vtkplotter_ to bring all the partitions together and show them just in one window.
Regards
Siegfried

**Comment by marcomusy** [comment]
@siegLoesch 
Hi Siegfried, I never thought of this possibility... and I never used mpiexec..
I will ask the dolfin experts! :)

**Comment by marcomusy** [comment]
Hi again, I was about to write a post on the fenics forum but then i found this... it looks that it would not be trivial if not at all impossible:
https://fenicsproject.discourse.group/t/how-to-merge-partial-results-to-a-combined-solution-in-mpirun/188
and
https://fenicsproject.discourse.group/t/how-to-solve-in-parallel-for-parametric-study/101/4
where the latter is probably not what we are looking for.

Moreover the `multiprocessing` thing I checked that is not working neither with vtkplotter nor with matplotlib..  (producing XIO errror).
