### ISSUE TITLE
Kernel dead when running notebook in a server

### ISSUE THREAD

**Issue by vianamp** [marcomusy/vtkplotter#37]
I have a Jupyter notebook running on a server on a specific port and IP. The notebook runs fine locally however, the kernel dies when I run the notebook from another computer. The line that crashes is `vp = Plotter(title='My title goes here')`.
I am running the notebook in the server with `jupyter notebook --no-browser --port=8080 --ip 10.xxx.xx.xx`. Access is done via `http://10.xxx.xx.xx:8080/?token=xxx`.  Could you guys think of something else I can try? Thanks.

**Comment by marcomusy** [comment]
What is the output of:
```python
# before importing anything

print(get_ipython())

from vtkplotter import settings

print(settings.notebookBackend)
print(settings.notebook_plotter)
```

**Comment by vianamp** [comment]
I got this

```
<ipykernel.zmqshell.ZMQInteractiveShell object at 0x7ff9fa85f8d0>
k3d
None
```

**Comment by marcomusy** [comment]
..looks normal.. ..so this is already crashing?
```
from vtkplotter import settings, Plotter

vp = Plotter()
```

**Comment by vianamp** [comment]
Yes, it crashes.

Could it be a Chrome-related problem?

**Comment by marcomusy** [comment]
might be.. what if you run this instead:
```python 
import k3d

vertices = [
    -10, 0, -1,
    10, 0, -1,
    10, 0, 1,
    -10, 0, 1,
]

indices = [
    0, 1, 3,
    1, 2, 3
]

plot = k3d.plot()
plot += k3d.mesh(vertices, indices)
plot.display()
```

**Comment by vianamp** [comment]
Both codes worked!

Just by specifying `screensize` fixed my code. Any idea why is that?

**Comment by vianamp** [comment]
Are you saying my 13inch screen isn't too big for the default screensize? :)

**Comment by marcomusy** [comment]
LOL ..no, that's because of a vtk call trying to get the physical size of your screen (which in your case does not exist since it on a server)..

It will be fixed in the next release, thanks for spotting the problem!
M.
