### ISSUE TITLE
Coloring faces of imported meshes

### ISSUE THREAD

**Issue by sariths** [marcomusy/vtkplotter#4]
Hi @marcomusy, 
I am trying to use your library to visualize data from thermal comfort studies. I have several manikins like the one shown below and I intend to color individual polygons based on the amount of thermal radiation incident on them (as shown in the screencapture in the second picture)
![vtk](https://user-images.githubusercontent.com/10361848/42423130-42f5a556-82f5-11e8-8210-ae84a2146f44.png)
![picture1](https://user-images.githubusercontent.com/10361848/42423133-52ee5be2-82f5-11e8-95d1-15ec4eaf7abf.png)
The part about loading the geometry is super simple due to the methods in your  `vtkPlotter` class. I could not find a way to interact with the individual faces of the obj through any of the methods. I also tried to understand the methods and attributes available at runtime through the debugger in Pycharm but could not get much far. Any suggestions?

Thanks,
Sarith

**Comment by marcomusy** [comment]
Hi 
I'm adding now this functionality and let you know asap
M

**Comment by sariths** [comment]
@marcomusy Thanks. Please let me know if I can help out in any way. I just got started with VTK but I do have some experience in Python and data visualization.

**Comment by marcomusy** [comment]
please have a look at examples/mesh_coloring.py

![mcol](https://user-images.githubusercontent.com/32848391/42451786-8277f664-8388-11e8-9ea7-3f5d2de522ff.png)

**Comment by sariths** [comment]
This is pretty incredible!! 

I just ran your example file with some of my manikins and it works great..
![2018-07-09 15_16_12-window](https://user-images.githubusercontent.com/10361848/42452825-6229a8be-838b-11e8-8acf-22614c245b95.png)
..and just for fun, I tried a more complex model (with nearly 100,000 surfaces and missing geometry) and that loads too!
![2018-07-09 15_13_13-window](https://user-images.githubusercontent.com/10361848/42452800-5d0c085e-838b-11e8-8df7-fcdfaceeda47.png)

I think this library could be used to visualize a whole lot of building science data in 3D. 
cc: @mostaphaRoudsari

**Comment by marcomusy** [comment]
Thanks,
keep in mind you can control the scalarbar to have it horizontal e.i.:
vp.addScalarBar(man3, horizontal=True)

**Comment by sariths** [comment]
@marcomusy Thanks for the tip. Which API do you to refer to for Python-specifc functionality within VTK? I have come across an API and documentation for the C++ version, however, it appears that not all the classes and methods have been ported over to the Python version.

**Comment by marcomusy** [comment]
I typically use the latest version of vtk (8.1 as it comes in anaconda) so I guess all the c++ methods are ported to python, older vtk versions might not have the latest features. I don't think that there is anything like a specific python api for reference...
If you load any mesh at command line you should be able to get a message of which version you are running, e.g.:
./plotter.py anymesh.obj

**Comment by sariths** [comment]
> I don't think that there is anything like a specific python api for reference...
That's the case with most libraries ported to Python, except PyQT. Anyway, thank you for getting this project started. I will circle back in case I come up with more "interesting" queries.

**Comment by LogWell** [comment]
[data](https://drive.google.com/open?id=1ICmSs2MBztxqI0ERWBey67RMBi-ox15-)

code:
```
from vtkplotter import *
import numpy as np

sc = load('scan_c.obj')
data_label = np.load('scan_labels.npy').reshape(-1)
sc.pointColors(data_label, alpha=1, mode='scalars')
show(sc, Text('seg', c='k'), bg='w', interactive=True)
```

question:

1,2: Shown in OpenFlipper and vtkplotter, difference caused by ?interpolation???
3,4: How to color a single element(vertex or face) without interpolation?
![view](https://raw.githubusercontent.com/LogWell/Markdown/master/prob.png)

PS: In `scan.obj`, only `v` and `vt` are stored, but `f` indexes to `vn`. It can be opened in meshlab and OpenFlipper, exception handling should be done, can you handle such abnormal data?

**Comment by marcomusy** [comment]
Hi @LogWell please pull the latest commit and try the following:

```python
from vtkplotter import load, show, colors
import numpy as np

sc = load('/home/musy/downloads/scan/scan_c.obj')
data_label = np.load('/home/musy/downloads/scan/scan_labels.npy').reshape(-1)

# Optionally build a lookup table of colors:
#                     scalar, color
lut = colors.makeLUT([( 0,   'pink'),
                      ( 1,   'green'),
                      ( 3,   'yellow'),
                      ], 
                      N=4, # specify total nr. of colors
                    )

sc.pointColors(data_label, cmap=lut).addScalarBar()

#sc.mapPointsToCells() # this would translate point data to cell data

# avoid interpolating cell colors:
sc.mapper.InterpolateScalarsBeforeMappingOff()
show(sc, bg='w')
```
![image](https://user-images.githubusercontent.com/32848391/68143889-b44e7880-ff32-11e9-9be6-1ced19f9bb37.png)

> PS: In scan.obj, only v and vt are stored, but f indexes to vn. It can be opened in meshlab and OpenFlipper, exception handling should be done, can you handle such abnormal data?

Unfortunately vtk seems unable to handle this faulty data..

> PS: How to set transparent background?

```python
from vtkplotter import settings
settings.screenshotTransparentBackground = True
```

**Comment by LogWell** [comment]
NOTE: The red dot in the leftmost yellow circle in the previous image may be caused by abnormal data `scan.obj` , correct as shown in fig_1, same as in vtkplotter.

Q:
1. How to color single point rather transm to face, like in fig_2?

2. Thanks for your example of using `colors.makeLUT`. I'm a little confused about setting the correct color in fig_3.

![fig](https://raw.githubusercontent.com/LogWell/Markdown/master/prob_2.png)

**Comment by marcomusy** [comment]
1. consider the following where points can be overlapped to mesh if you wish:
```python
from vtkplotter import load, show, makeLUT, Points
import numpy as np

sc = load('/home/musy/downloads/scan/scan_c.obj')
data_label = np.load('/home/musy/downloads/scan/scan_labels.npy').reshape(-1)

# build a lookup table of colors:
#              scalar, color
lut = makeLUT([( 0,   'red'),
               ( 1,   'green'),
               ( 3,   'gold'),
               ], 
               N=4, # specify total nr. of colors
              )

sc.pointColors(data_label, cmap=lut).addScalarBar()

# avoid interpolating cell colors:
sc.mapper.InterpolateScalarsBeforeMappingOff()

pts = Points(sc.coordinates()).pointColors(data_label, cmap=lut)

show(sc, pts, N=2, bg='w')
```
![image](https://user-images.githubusercontent.com/32848391/68217007-292cbb80-ffe2-11e9-8e78-29dd1123c7bb.png)


2. make sure you have pulled the latest version from git. 
note that in your scalar file you only have values 0,1,3 and 2 is absent.
Plus you have a typo "bule" instead of "blue".

Let me know if you can reproduce the above figure.

**Comment by LogWell** [comment]
In fact, there are four labels in total(maybe more). The current obj file only contains three of them (label 2 may represent skirt).

For a batch of data, I can map 0,1,2,3 to four colors, and then color it according to the label information.

**Comment by marcomusy** [comment]
@LogWell 

I realized that my first try at fixing this was not great.. :) I modified the makeLUT() function, so the above now becomes:
```python
from vtkplotter import load, show, makeLUT, Points
import numpy as np

sc = load('/home/musy/downloads/scan/scan_c.obj')
data_label = np.load('/home/musy/downloads/scan/scan_labels.npy').reshape(-1)

# build a lookup table of colors:
#              scalar, color  alpha
lut = makeLUT([( 0,   'red'       ),
               ( 1,   'green', 0.5),
               ( 3,   'gold'      ),
               ],
              interpolate=False,
              )

sc.pointColors(data_label, cmap=lut).addScalarBar()

# avoid interpolating cell colors:
sc.mapper.InterpolateScalarsBeforeMappingOff()

pts = Points(sc.coordinates()).pointColors(data_label, cmap=lut)

show(sc, pts, N=2, bg='w')
```
this also includes setting opacities if a 3rd element is given in the list.
Hope this works for you.

**Comment by LogWell** [comment]
Hi, marcomusy~

[data](https://rec.ustc.edu.cn/share/25487fd0-5957-11ea-bb77-337001231890)
![](https://raw.githubusercontent.com/LogWell/Markdown/master/%E6%97%A0%E6%A0%87%E9%A2%98.png)

The result seems strange after I subdivided the mesh. It looks a little bit like a flip from the inside view, but the normal of faces are correct in meshlab.

How to solve this problem?

**Comment by marcomusy** [comment]
Hi @LogWell 
this looks related to a transparency problem in vtk.. though I must say I don't understand exactly why that happens.. This works for me:
```python
from vtkplotter import *

settings.useDepthPeeling = True

m = load('00000.obj').texture('registered_tex_1_m.png')
m.show(axes=4)
```

**Comment by LogWell** [comment]
How to render a mesh like this:

![20200816_15:26:45](https://user-images.githubusercontent.com/34391447/90329222-4a8cf000-dfd5-11ea-8935-f02a861d9e7f.png)
![20200816_15:28:34](https://user-images.githubusercontent.com/34391447/90329223-4eb90d80-dfd5-11ea-8d06-c15fca64244f.png)
![image](https://user-images.githubusercontent.com/34391447/90329245-7019f980-dfd5-11ea-988f-db7e48a8288d.png)

**Comment by marcomusy** [comment]
various possibilities..:
if the points are projectable onto a plane (which seems to be the case) you can discard the existing triangles and recreate a new mesh with `delaunay2D`
or 
try to recreate it with `recoSurface()`
besides
you can use `clean(tol=0.01)` to preprocess and reduce the points and/or use `smoothMLS2D()` to make the surface smoother.

finally - once you have the mesh - you can color the outside and inside differently with `color()` and `backColor()`
