### ISSUE TITLE
Inconstant behaviors of shapes.py w.r.t `normal`

### ISSUE THREAD

**Issue by MiaoDX** [marcomusy/vtkplotter#40]
Hi,
I used your lib to calc some cubes for vis, which was nice. However, It seems that you choose to omit normal computation with [commit jupyter support](https://github.com/marcomusy/vtkplotter/commit/2c1a3b8e643fcc1bd8c258f2e6242d46fb89b8d3), 
which is one kind of nice choice to remove these somehow duplicated codes. However, the helper docs are not updated, `Polygon/Disc/Box/Cube` still have `normal` function helper. And what is more, `Grid/Plane` still keeps normal parameter.
So, why this somehow brute decision is made (break backward compatibility) and again, why behaviors are not constant? And is there a better replacement for transform with normal?
Looking forward to your reply.

**Comment by marcomusy** [comment]
Hi @MiaoDX thanks for your input,
I will fix the documentation in the next release. It is true that for Grid and Plane there is the `normal` keyword and not for other shapes objects ... although I think it can be justified as it comes more natural to specify this property at creation time.
For the others you can still rotate and/or set orientation like in this example:
```python
from vtkplotter import *

#c = Cube() #.rotateX(90).pos(3,3,3) #alternatively: set a rotation
c = Text('MiaoDX', pos=[0,0,0])

#this line will not be needed from next release on:
#(it defines an intrinsic axis for the object)
c.base, c.top = vector(0,0,0), vector(0,0,1)

c.orientation([1,1,1]) # re-orient the intrinsic axis along this vector

show(Point(), c.lw(0.1), axes=1, bg='w')
```
![image](https://user-images.githubusercontent.com/32848391/60447016-d6ea2100-9c22-11e9-92ce-cd25e77c71a2.png)

This [example](https://github.com/marcomusy/vtkplotter/blob/master/examples/simulations/gyroscope1.py) might be relevant too,
Hope this helps
M.

**Comment by MiaoDX** [comment]
Yeah, the `.rotateX(90).pos(3,3,3)` seems enough, thanks!
