### ISSUE TITLE
vtu files, multiple fields

### ISSUE THREAD

**Issue by fdeheeger** [marcomusy/vtkplotter#41]
very convenient to explore VTK files inside jupyter.

The example gallery is great but I cannot find a simple example of a direct show of a vtu file while picking the right scalar field to be presented on the mesh. 
Any hints ?

**Comment by marcomusy** [comment]
Hi try for ex:
```python
from vtkplotter import *

mesh = load(datadir+'pulley.vtu')

mesh.addPointScalars(mesh.coordinates()[:,0], 'my_x')
mesh.addPointScalars(mesh.coordinates()[:,1], 'my_y')
mesh.addPointScalars(mesh.coordinates()[:,2], 'my_z')

mesh.scalars('my_y') # or mesh.scalars(2)
printInfo(mesh)

show(mesh)
```

Inside jupyter:

![image](https://user-images.githubusercontent.com/32848391/60973780-2dddad80-a329-11e9-91c3-ac0b46444ef3.png)

(the actual printout format will be a bit different)

**Comment by fdeheeger** [comment]
Thanks a lot for your help. `printInfo` does help a lot.
