### ISSUE TITLE
vtkplotter and PyQt

### ISSUE THREAD

**Issue by hmralavi** [marcomusy/vtkplotter#45]
Hello Marco,
I need to work with 3D meshes inside my PyQt GUI.
As you might know, using `vtk.qt.QVTKRenderWindowInteractor` we can add a vtk renderer window to our PyQt.
I was wondering if there is some way to do the same with vtkplotter.
thanks.

**Comment by marcomusy** [comment]
HI @hmralavi , check out a couple of example here:
https://github.com/marcomusy/vtkplotter/blob/master/examples/other/qt_window.py
https://github.com/marcomusy/vtkplotter/blob/master/examples/other/qt_window_split.py
cheers

**Comment by hmralavi** [comment]
> HI @hmralavi , check out a couple of example here:
> https://github.com/marcomusy/vtkplotter/blob/master/examples/other/qt_window.py
> https://github.com/marcomusy/vtkplotter/blob/master/examples/other/qt_window_split.py
> cheers

**Comment by hmralavi** [comment]
Thanks @marcomusy they were helpful.
I also ran into a bug with both examples. when I hit the "S" key to capture screenshot, the resulting screenshot is a black image.
