### ISSUE TITLE
Can't pickle Actors

### ISSUE THREAD

**Issue by hmralavi** [marcomusy/vtkplotter#46]
I get an error when I want to write actors to a pickle file.
```
import vtkplotter
import pickle

obj = vtkplotter.Sphere()

data = {'actors': obj}
with open('actors.pickle', 'wb') as f:
    pickle.dump(data, f)
```

> TypeError: can't pickle Actor objects

**Comment by marcomusy** [comment]
Hi, you cannot pickle vtk objects, but you can still save single or multiple object to file, eg:
```python 
from vtkplotter import *

obj1 = Sphere()
obj2 = Torus().pos(0,0,1)

# single mesh
obj1.write('mysphere.vtk')

# multiple meshes/volumes
write([obj1, obj2], 'myobjs.npy')
```
then you can read them back with `vtkplotter.load()` or in terminal by command line:
`> vtkplotter myobjs.npy`
