### ISSUE TITLE
Silhouette not updating when changing camera position

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vtkplotter#48]
I'm trying to add an outline to my actors. This is an attempt to create a cell-shading like appearance without having to manually edit the shaders.

I create an outline by adding a vtkPolyDataSilhouette to the polydata. This works fine in vtk, the outline updates when the camera changes position.

However when I create an vtkplotter Actor the outline no longer gets updated.
It does not matter whether I create the outline using the Actor.silhouette function or create an Actor from the vtkActor. 

Somehow the update-connection is lost when the vtkActor is converted to a vtkplotter Actor.

As a work-around I tried adding the vtkActors to the rendered manually, but they get deleted from the render in the show().

```
from vtkplotter import *

# --------- 1. First attempt -------

p = Plotter()
a = Cone()
s = a.silhouette(direction=p.renderers[0].GetActiveCamera())  # p.camera is None until p.show is called
s.lw(3)

a.alpha(0.3)
p.add(a)
p.add(s)
p.show()  # <--- outline is not updated when camera position changes

# ------ 2. and now using raw vtk :: This works ------

import vtk

renderer = vtk.vtkRenderer()
renderer.SetBackground(1,1,0)

renderWindow = vtk.vtkRenderWindow()
renderWindow.SetSize(640, 480)
renderWindow.AddRenderer(renderer)

interactor = vtk.vtkRenderWindowInteractor()
interactor.SetRenderWindow(renderWindow)

dataset = a.GetMapper().GetInputAsDataSet()

outline = vtk.vtkPolyDataSilhouette()
outline.SetInputData(dataset)
outline.SetEnableFeatureAngle(True)
outline.SetBorderEdges(True)
outline.SetCamera(renderer.GetActiveCamera())
outlineMapper = vtk.vtkPolyDataMapper()
outlineMapper.SetInputConnection(outline.GetOutputPort())

actor = vtk.vtkActor()
actor.SetMapper(outlineMapper)
actor.GetProperty().SetColor(0,0,0)
actor.GetProperty().SetLineWidth(3)
renderer.AddActor(actor)

renderWindow.Render()
renderer.ResetCamera()
interactor.Start()   # <---- Outline updates when camera position changes

# --------- 3. and finally again with vtkplotter

vpa = Actor(actor)  # <-- Create an vtkplotter actor based on the vtkActor
p2 = Plotter()
p2.add(vpa)
p2.show()

**Comment by RubendeBruin** [comment]
Work-around using qt:

Create Plotter
Create Actor
Plotter.show()

create vtkActor with silhouette based on Actor
manually add to plotter.renderer[0]

![afbeelding](https://user-images.githubusercontent.com/34062862/64201960-403f1800-ce90-11e9-8c07-dfdced24f104.png)

[vtkPlotterOutline.py.txt](https://github.com/marcomusy/vtkplotter/files/3571092/vtkPlotterOutline.py.txt)

**Comment by marcomusy** [comment]
Hi Ruben
I could only reduce the above code to:
```python
from vtkplotter import *
import vtk

plt = Plotter(bg='lightblue', interactive=False)

a = Cone().alpha(0.2).flat().c('gold').lw(0.1).lc('red')
plt += a
plt.show() 

outline = vtk.vtkPolyDataSilhouette()
outline.SetInputData(a.polydata())
outline.SetCamera(plt.camera)
outlineMapper = vtk.vtkPolyDataMapper()
outlineMapper.SetInputConnection(outline.GetOutputPort())
# outlineMapper.SetInputData(outline.GetOutput()) # <------

actor = Actor()
actor.SetMapper(outlineMapper)
actor.lw(4).c('black')

plt.add(actor) # add() also calls Render()
interactive()
```
![image](https://user-images.githubusercontent.com/32848391/64207124-44713280-ce9c-11e9-9a88-8da23a95d9d7.png)

The problem is probably in the commented-out line, in the difference between `SetInputConnection` vs `SetInputData` (which is what is done internally in vtkplotter).. I'll think if there is a possible workaround that works in the general case... 
Thanks for spotting it!
M
