### ISSUE TITLE
Plotter background image not working when N>3

### ISSUE THREAD

**Issue by ebc0007** [marcomusy/vtkplotter#49]
It may just be my inexperience, but I am unable to get a background image to work properly for a plotter when N is greater than 3 or if the plotter shape is more than 1 row. I plan to eventually use the plotter to randomly place an actor on top of the image and save a screenshot so the ability to have more than one row is a major plus. 

The below code will produce the desired output of the background image (N is less than 3).
```

from vtkplotter import *

vp = Plotter(N=2, axes=0, size=(600,800), bg=datadir+"images/tropical.jpg")

vp.show(interactive=1)


```
![2019-09-05 14_34_04-Visualization Toolkit - Win32OpenGL #1](https://user-images.githubusercontent.com/54959180/64375032-a344c200-cfea-11e9-8f4c-b62820e6bef3.png)

However, after running the following code, you see that rows of the plotter just turn black instead of displaying the background image.

```

from vtkplotter import *

vp = Plotter(N=9, axes=0, size=(600,800), bg=datadir+"images/tropical.jpg")

vp.show(interactive=1)

```

![2019-09-05 14_34_41-Visualization Toolkit - Win32OpenGL #1](https://user-images.githubusercontent.com/54959180/64375082-bfe0fa00-cfea-11e9-8dbd-8e647f6d8c3e.png)

Any help is greatly appreciated!

**Comment by marcomusy** [comment]
Hi @ebc0007 
this should be fixed in the latest commit, try:
```bash
git clone https://github.com/marcomusy/vtkplotter.git
cd vtkplotter/examples/basic
python bgImage.py
```
![image](https://user-images.githubusercontent.com/32848391/64491365-3dfe0480-d268-11e9-836c-c6f4fbf88d25.png)

note that you can also use `Plotter(shape=(3,4), ..)` to define the window geometry.

**Comment by ebc0007** [comment]
Thanks for such a quick response!
