### ISSUE TITLE
Isolines in surface: can't remove them by input

### ISSUE THREAD

**Issue by thiago-springer-jota** [marcomusy/vtkplotter#50]
![VTKLine1VisibleFalse](https://user-images.githubusercontent.com/50302382/64578261-e5ecfe00-d34c-11e9-8103-c714689732a5.png)
![VTKLine1VisibleTrue](https://user-images.githubusercontent.com/50302382/64578262-e5ecfe00-d34c-11e9-87be-a9355a065b27.png)

I am new to vtkplotter. I attached a couple of pictures that explain the issue. 

I can't get rid of those contour lines unless I manually uncheck visibility of "line #1" after the plot command is issued. I never explicitly issued a command to generate "line #1".

Is there a way to not get those lines by default? I checked all options; maybe I missed something.

Thanks for the help

**Comment by marcomusy** [comment]
Hi
just set `zlevels=0` in `fxy` (not in `show`):
```python
from vtkplotter import Plotter, fxy, sin, cos

def my_z(x, y):
    return sin(2 * x * y) * cos(3 * y) / 2

f1 = fxy(my_z, zlevels=0).c('lightblue')

f1.show(viewup='z')
```
![image](https://user-images.githubusercontent.com/32848391/64606283-32c0eb00-d3c6-11e9-95c7-c96300b27c7d.png)

at present isolines do not work in notebooks..
Hope this helps
