### ISSUE TITLE
Semi transparent objects rendering

### ISSUE THREAD

**Issue by FedeClaudi** [marcomusy/vtkplotter#53]
Hello, 

I have been using vtkplotter do develop an application to render anatomical data of the mouse brain in python (https://github.com/BrancoLab/BrainRender). 

It has been working great so far, the only problem I have found is when I display multiple actors (brain regions) with `alpha < 1`. Then, when the scene is rendered it looks weird:

![image](https://user-images.githubusercontent.com/17436313/65498506-ed1b1c80-deb3-11e9-827a-9f104edbda5e.png)

for instance here the two structures circled in blue should be behind the larger one circled in red. 
This seems to be a consistent bug: with multiple semi-transparent object they are not rendered so that an object behind another is partially hidden. The effect is even more evident when the objects have multiple colors. 

Because of how densely structured the brain is, it's crucial to be able to display structures with some transparency so that you can see what's behind the surface, so it would be great if you could advise a way to fix this. 

Thank you, 
Federico

**Comment by marcomusy** [comment]
Hi Federico
cool project! I think this is a general vtk-related problem, as vtkplotter has no control over it.
Probably it's fixable by setting:
```python
from vtkplotter import settings
settings.useDepthPeeling = True
# settings.useFXAA = True
```
(perhaps with some combination of the two flags).
See also related example [here](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/mesh_bands.py) where actually one can reproduce the issue by setting `useDepthPeeling=False`.
Hope this helps!
Marco

**Comment by FedeClaudi** [comment]
Hi Marco, 

That fixed it!

Just an unrelated question (don't want to open an issue for this): are there ways to improve performance? 
I've had some users who expressed the desire to rendered large number of objects (10k - 1M spheres ), but when I tried it my computer started complaining at about 10k objects. Any idea?

Thank you very much, 
Federico

**Comment by marcomusy** [comment]
Cool!

..if you create many actors independently at some point you will lose performance.. things you can do are:
- reduce the number of vertices/resolution in meshes (e.g. with `shapes.Sphere(res=10)`
- decimate large meshes (`actor.decimate(fraction)`)
- substitute `Sphere` with `Points` (or `Spheres`)
- use glyphs for repeated objects, see examples:
 [manyspheres.py](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/manyspheres.py), [manypoints.py](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/manypoints.py) and [glyphs.py ](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/glyphs.py) or [glyphs_arrows.py
](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/glyphs_arrows.py)

Let me know if this improves speed/memory
Cheers, Marco
