### ISSUE TITLE
How to save screenshot without show()?

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vtkplotter#55]
1. load the mesh file
2. color each face
3. save the rendered image(there's no need to show)

I don't know how to implement the above without `show()`, thanks~

Ref: [here](https://github.com/marcomusy/vtkplotter/issues/28#issuecomment-501397743),

**Comment by marcomusy** [comment]
You cannot save a screenshot without rendering the scene with `show()`, but you can avoiding visualizing the rendering window using keyword `offline`: e.g.
```python
from vtkplotter import *

vp = Plotter(axes=0, offscreen=True)

for i in [1,2,3]:
    text = Text('%03d' %i, c='white')
    vp += Sphere(c=i).x(i)
    vp += text
    vp.show()
    screenshot('test_%03d.png' %i)
    vp -= text
```
about coloring faces individually check [here](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/colorMeshCells.py): e.g.

```python
from vtkplotter import *

sc = load(datadir+'cow.vtk')

cols = []
for i in range(sc.NCells()):
    cols.append(i) # i-th color or (r,g,b)

sc.cellColors(cols, mode='colors')

show(sc, bg='white')
```
