### ISSUE TITLE
How to view mesh sequence?

### ISSUE THREAD

**Issue by LogWell** [marcomusy/vtkplotter#56]
Bother again ~~~

How to browse the mesh sequence like browsing pictures under the folder in a simple and elegant way! Sometimes it's useful. Maybe it can be put into the basic examples.

By the way, when I loaded the mesh with texture, the result was incorrect, what is the reason for this?

THANKS!!!

**Comment by marcomusy** [comment]
Hi, thanks, can you describe in what way it looks incorrect or post a snapshot?

**Comment by LogWell** [comment]
[data](http://rec.ustc.edu.cn/share/cf858350-e52d-11e9-85bf-1f24a1337a4c)
```
from vtkplotter import *
s = load('BWom0317-HD2-O02P01-S.obj', c="white")
s.texture('BWom0317-HD2-O02P01-S-BWom0317-HD2-O02P01-D.jpg')
s.show()
```

**Comment by marcomusy** [comment]
Hi, I just committed a fix for the texturing, try:
```bash
git clone https://github.com/marcomusy/vtkplotter.git
cd vtkplotter
pip install .
```
then
```python
from vtkplotter import load

q = load('BWom0317-HD2-O02P01-S.obj')
q.texture('BWom0317-HD2-O02P01-S-BWom0317-HD2-O02P01-D.jpg')
q.lighting('glossy')

q.show(bg='w')
```
![Screenshot from 2019-10-02 18-56-37](https://user-images.githubusercontent.com/32848391/66065394-919dfe00-e547-11e9-9507-c7262463e163.png)

to browse a sequence of meshes you can do it with command line:
`vtkplotter -s mymeshes*.obj`
or
`vtkplotter -n mymeshes*.obj # each in a subwindow`

**Comment by NaGenhao** [comment]
^_^

If meshes are located in different folders, I can gather them into a list. And what should I do to make it as convenient as switching back and forth under the same folder like `vtkplotter -s mymeshes*.obj`?

**Comment by marcomusy** [comment]
sorry, i'm not sure I understand the question... what you can do is:
`vtkplotter -s folder1/mymeshes*.obj folder2/othermeshes*.vtk`

**Comment by NaGenhao** [comment]
It's when there are too many files and they're scattered.

```
path_objs = ["/F/p1/a1/00.obj", 
             "/F/p1/a1/01.obj", 
             ...,
             "/F/p1/a2/00.obj", 
             "/F/p1/a2/01.obj",
             ...,
             ...,
             "/F/p2/a1/00.obj", 
             "/F/p2/a1/01.obj",
             ...,
             "/F/p2/a2/00.obj",
             ...]
```
In fact, it is just `person(n) + action(m) + frame(i)`.

In python, I can use
```
st = ' '.join(path_objs)
os.system('vtkplotter -s ' + st)
```

Is there any other convenient way to implement? Although this is very intuitive.HAHA~

**Comment by marcomusy** [comment]
Oh I see.. you can do it programmatically but you will need to write a custom slider function :)
See this [example](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/slider_browser.py).

**Comment by NaGenhao** [comment]
OK, intresting.

I'm going to implement keyboard control instead of "Scrolling", like "↑, ↓, ←, →".
