### ISSUE TITLE
Export high quality figures?

### ISSUE THREAD

**Issue by HakamShams** [marcomusy/vtkplotter#57]
Hallo,

How can I save high quality figures from the rendering window e.g. 300 dpi or more? When I save screenshot even with svg or eps, the quality is not good at all !

Thanks in advanced

Hakam Shams

**Comment by marcomusy** [comment]
Hi Hakam,
to my knowledge vtk cannot export to eps/svg, yet you can increase a lot the dpi using:
```python
from vtkplotter import settings

settings.screeshotScale = 2 # integer factor

# ...

screenshot()
```
you can also increase the `Plotter` window size: e.g.
```python
vp = Plotter(size=(1500,1500))
```
Hope this helps

**Comment by HakamShams** [comment]
First thank you it works! but there is still something weird. When I increase the scale e.g. to 2 the screenshot seems to be a stitching from the original scale and the new one!

![screenshot](https://user-images.githubusercontent.com/49558174/66071155-ef841300-e552-11e9-98b1-15443f3968c5.png)

**Comment by marcomusy** [comment]
this seems related to a bad behavior of the `vtkWindowToImageFilter` class on some systems...
by looking into the vtk documentation I've found something which is probably a better solution:
```python
from vtkplotter import *

s = Sphere().wireframe()
plt = s.show(axes=1, bg='w', interactive=False) # return Plotter obj

import vtk
renderLarge = vtk.vtkRenderLargeImage()
renderLarge.SetInput(plt.renderer)
renderLarge.SetMagnification(3)
renderLarge.Update()

write(renderLarge.GetOutput(), 'screenshot.png')

interactive()
```

let me know if this works for you!

**Comment by HakamShams** [comment]
this solution works for the original camera view, which is defined in (plt in the code).
what I do now, I move the mouse and get my camera view by pressing (key C), then rerun the code defining these parameters with your solution.

But it helps a lot now, thank so much

**Comment by s1291** [comment]
@marcomusy 
Hello,
In VTK, I think, there is a class named [vtkSVGExporter](https://vtk.org/doc/nightly/html/classvtkSVGExporter.html). In paraview it uses the library gl2ps library to generate multiple vector format outputs (eps, pdf, svg).

Regards

**Comment by marcomusy** [comment]
Thanks @s1291 if i understand correctly this is only applicable to exporting `vtkContext2D` scenes..
Do you have more info on how gl2ps is used in paraview?

**Comment by s1291** [comment]
Unfortunately, right now, I don't know how it is used by Paraview.

**Comment by vigji** [comment]
@marcomusy I would be very interested to know if anything comes out about exporting 3D scenes as vector images!

**Comment by marcomusy** [comment]
@vigji this very much depends on the upstream vtk, I'll let you know if anything happens on that front!
