### ISSUE TITLE
AttributeError: 'Plotter' object has no attribute 'shape'

### ISSUE THREAD

**Issue by ga62ris** [marcomusy/vtkplotter#61]
File ".../anaconda3/lib/python3.7/site-packages/vtkplotter/backends.py", line 85, in getNotebookBackend
    if vp.shape[0] != 1 or vp.shape[1] != 1:

AttributeError: 'Plotter' object has no attribute 'shape'

why do i get this error after installing k3d ? worked before that.

**Comment by marcomusy** [comment]
Thanks for spotting the issue, please try the upgraded version:
`pip install vtkplotter -U`

**Comment by ga62ris** [comment]
no attribute errors anymore, but the plotter isn't opening/starting

**Comment by marcomusy** [comment]
try to restart the browser? you can try one of the examples in 
https://github.com/marcomusy/vtkplotter/tree/master/examples/notebooks

**Comment by ga62ris** [comment]
tried different examples, the scripts run through, but plotter isn't starting.

**Comment by marcomusy** [comment]
that's weird.
what is you system OS and python version?
do you get any output window when setting `embedWindow(False)`?

**Comment by ga62ris** [comment]
weird indeed. It works when script is run in the terminal. 
problem seems to be the IDE (Spyder 3.3.6). 
macOS 10.14.6 | python 3.7.0
when adding the suggestion, this occurs: 
Error in show(): wrong renderer index 0

**Comment by marcomusy** [comment]
OK! I see now the problem.. the ipython console of spyder cannot embed the graphics backend.
One way out is to disable it with e.g.:
```python
from vtkplotter import Cone, show, settings

settings.notebookBackend = False

for i in range(10):
    Cone().x(2*i).color(i) # no variable assigned

# three points, aka ellipsis, retrieves the list of all created objects
show(..., axes=1, viewup='z')
```

**Comment by ga62ris** [comment]
Yes that solves the issue! 
Something not directly related to the previous error: 
When trying to load a DICOM file(vtkplotter -g pathDICOMfile ), there appears an Error in load()
Is there an example in the example library which shows this ?
Is it possible to both load DICOM single files and DICOM dataset files ?

**Comment by marcomusy** [comment]
Cool!

About dicom: to my knowledge dicom files are grouped into directory so you cannot read them individually, this is reflected by the `vtkDICOMImageReader` class (see
https://vtk.org/doc/nightly/html/classvtkDICOMImageReader.html)
