### ISSUE TITLE
Adding vtkplotter to FEniCS Docker container: vtkplotter can't render with error "ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 1223 vtkXOpenGLRenderWindow (0x24992f0): bad X server connection. DISPLAY=Aborted (core dumped)" 

### ISSUE THREAD

**Issue by SiriusFuenmayor** [marcomusy/vtkplotter#64]
Hello, I have succesfully build a FEniCS Docker container incluiding vktplotter, but when I try to use vtkplotter I encounter the error:

`ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 1223 vtkXOpenGLRenderWindow (0x24992f0): bad X server connection. DISPLAY=Aborted (core dumped)`

It appears that vtkplotter or vtk can not run without the X server. Is there any way to solve this issue?

**Comment by marcomusy** [comment]
I'm afraid this is related to the X server trying to export the display...
Check out https://discourse.paraview.org/t/pvpython-bad-x-server-connection/849/5

**Comment by SiriusFuenmayor** [comment]
I am using offscreen=True in my plotting command but the error persists.

I will try to run an X server inside the Docker container, lets see what happen. But if there is a shortcut I will appreciate the info

**Comment by SiriusFuenmayor** [comment]
Hello Marco, there is a way to only store images rendered by vtkplotter without using the X server?

something like this:

```
import vtkplotter.dolfin as vtkplot
vtkplot.plot(u, offscreen=True, azimuth=-30.0, elevation=30.0, axes=0)
vtkplot.screenshot(filename='./outputVTK/u.png')
```

**Comment by marcomusy** [comment]
I'm not sure but I suspect that it might not be possible..

**Comment by SiriusFuenmayor** [comment]
Hi Marco, I was able to build the Docker container with FEniCS and vtkplotter and to render using SSH with X11 forwarding. I don't know what will be the best way to share this info with you an others I think I will make a post in the FEniCS forum. What do you think?

**Comment by marcomusy** [comment]
Hi, that would be great if you have a recipe to share it could be followed by others.. I guess this is the thread: https://fenicsproject.discourse.group/t/how-to-add-a-python-module-to-the-fenics-docker-container/1665/2
thanks!
Marco

**Comment by LogWell** [comment]
Hi, marcomusy.

How to render on the server?

There is a large amount of data on the server to be checked, Blender (cycle) and pyrender are time consuming(compared with vtkplotter locally), but I don't know how to set it up for offscreen rendering on the server.
![example](https://raw.githubusercontent.com/LogWell/Markdown/master/bman0103hd2o03p01s.png)

**Comment by marcomusy** [comment]
Hi @LogWell 
From the above discussion and related links I get that you need X11 to be able to save screenshots even if no window is opened.
I understand that @SiriusFuenmayor has already found way to do it.

**Comment by RubendeBruin** [comment]
I don't see any clear instructions on how to make this work yet, so I'm just reporting what worked for me on ubuntu 18.04 server. This is based on the instructions provided for pyvista: <https://docs.pyvista.org/getting-started/installation.html>

1. install libgl1-mesa and xvfb:

`sudo apt-get libgl1-mesa-dev xvfb`

2. execute on startup:

`#!/bin/bash`
`set -x`
`export DISPLAY=:99.0`
`which Xvfb`
`Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &`
`sleep 3`
`set +x`
`exec "$@"`

I saved the code above as  /etc/rc.local and used chmod +x to make it executable. It does throw an error during startup but it does work.

`vp.settings.notebookBackend = False`
`vp.settings.screeshotScale = 2`
`offscreen = vp.Plotter(axes=0, offscreen=True, size=(h,w))`
`offscreen.add(actors)`
`offscreen.show(camera=camera)`
`for r in offscreen.renderers:`
`      r.SetBackground(1,1,1)`
`      r.UseFXAAOn()`
`vp.screenshot(filename)`

**Comment by XushanLu** [comment]
Hi,

I tried this on my Ubuntu 22.04 LTS system connected via SSH. Both the test suggested here and my own script failed with the following error: 
[1]    6992 abort (core dumped) 

I believe I have installed all the libraries mentioned and set up the rc.local file both in /etc/ and in the folder that I am working in. 

Is anyone experiencing such an error?

Thanks.

**Comment by fstrazzante** [comment]
Hello,
thank you Marco for the module is amazing!
I still have this problem on Ubuntu server 20.04.
When I try to execute
```
import vedo
plt = vedo.Plotter(offscreen=True)
plt += vedo.Cube()
plt.show()
plt.screenshot("a.png")
plt.close()
```
I get:
```
Aborted
```

I installed all the packages suggested by RubendeBruin's answer and executed the bash script. For the bash script I executed on the server `which bash` and got `/usr/bin/bash` so, this is the bash script:
```
#!/usr/bin/bash

set -x
export DISPLAY=:99.0
Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
#sleep 3
set +x
exec "$@"
echo Just a regular string
```
I did `chmod u+x set_xvfb.sh`, executed with `./set_xvfb.sh` and got this output:
```
+ export DISPLAY=:99.0
+ DISPLAY=:99.0
+ set +x
Just a regular string
+ Xvfb :99 -screen 0 1024x768x24
```
And then, executing the python script, I still have:
`Aborted`

(Context)
Vedo: `2022.4.2`
vtk: `9.2.5`
Python: `3.8.10`
Ubuntu: `Ubuntu 20.04.5 LTS`


Anyone know how to resolve this?

**Comment by marcomusy** [comment]
Hi Francesco,
are you also getting the same problem if you run this script?
```python
#!/usr/bin/env python
#
import vtk
import time

cone = vtk.vtkConeSource()

mapper = vtk.vtkPolyDataMapper()
mapper.SetInputConnection(cone.GetOutputPort())

actor = vtk.vtkActor()
actor.SetMapper(mapper)

ren = vtk.vtkRenderer()
ren.AddActor(actor)

renWin = vtk.vtkRenderWindow()
renWin.SetSize(500, 500)
renWin.AddRenderer(ren)

# iren = vtk.vtkRenderWindowInteractor()
# iren.SetRenderWindow(renWin)

renWin.SetOffScreenRendering(1)
renWin.Render()
```

**Comment by fstrazzante** [comment]
Hi Marco,
thank you, I tried to execute the script you shared and I got this error:
```
 2023-02-02 08:33:45.587 (   2.324s) [        ACC37740]vtkXOpenGLRenderWindow.:464    ERR| vtkXOpenGLRenderWindow (0x25dfd00): bad X server connection. DISPLAY=
Aborted
```
