### ISSUE TITLE
Error in show(): wrong renderer index 0 

### ISSUE THREAD

**Issue by SiriusFuenmayor** [marcomusy/vtkplotter#65]
After installing the last version of vtkplotter I can't plot normally. Trying a simple plot with

```
from vtkplotter.dolfin import *
plot(u)
```

gives me the error

`Error in show(): wrong renderer index 0 `

**Comment by marcomusy** [comment]
that's strange.. it works on my system (ubuntu), from a normal python terminal..
are you sure you are running the latest version? is it in a jupyter notebook? try
`pip install vtkplotter -U`
