### ISSUE TITLE
I can plot my mesh but not dolfin.Expression with jupyter and embedWindow(backend='itkwidgets')

### ISSUE THREAD

**Issue by SiriusFuenmayor** [marcomusy/vtkplotter#67]
I am using FEniCS/Dolfin in Docker version with a Jupyter notebook. I am able to view my mesh with the code:

```
from vtkplotter.dolfin import embedWindow, plot
embedWindow(backend='itkwidgets') # backends are: itkwidgets, k3d or False
plot(mesh)
```
![Screenshot from 2019-10-13 20-37-31](https://user-images.githubusercontent.com/8355915/66724901-6d6cd780-edf9-11e9-971c-031050a8512a.png)

but when I try to pass dolfin.Expression to plot() I get the error

`Warning: no objects to show, check mode in plot(mode="...")
`
this is my code

```
mesh = Mesh('./geometry/brazo.xml')
subdomains = MeshFunction("size_t", mesh, './geometry/brazo_gmsh-physical.xml')
boundaries = MeshFunction('size_t', mesh, './geometry/brazo_gmsh-geometrical.xml')

V = FunctionSpace(mesh, 'P', 1)
V0 = FunctionSpace(mesh, 'DG', 0)
dx = Measure('dx', domain=mesh, subdomain_data=subdomains)

eps_0 = 8.85e-12
eps_musculo = 6.60e+1 
eps_piel = 7.29e+1
eps_grasa = 1.27e+1
eps_hueso = 1.53e+1
eps_medula = 2.43e+1

class Permittivity(UserExpression): 
   
    def __init__(self, materials, **kwargs):
        self.materials = materials
        super().__init__(**kwargs) 
   
    def eval_cell(self, values, x, cell):

        if self.materials[cell.index] == 1:
            values[0] = eps_piel
        elif self.materials[cell.index] == 2:
            values[0] = eps_grasa
        elif self.materials[cell.index] == 3:
            values[0] = eps_hueso
        elif self.materials[cell.index] == 4:
            values[0] = eps_hueso     
        elif self.materials[cell.index] == 5:
            values[0] = eps_musculo
    
epsilon = Permittivity(subdomains, degree=1)
from vtkplotter.dolfin import embedWindow, plot
embedWindow(backend='itkwidgets') # backends are: itkwidgets, k3d or False
plot(epsilon)

```
result:

![Screenshot from 2019-10-13 20-41-15](https://user-images.githubusercontent.com/8355915/66724940-fa179580-edf9-11e9-93df-f5d6840cdc48.png)

**Comment by marcomusy** [comment]
it;'s difficult to reproduce the problem without the meshes..
does it work with `embedWindow(False)`? What version of fenics?
The most similar example I can find is [this](https://github.com/marcomusy/vtkplotter/blob/master/examples/other/dolfin/magnetostatics.ipynb).
I would first check if that works.

**Comment by RuruX** [comment]
Hi Marco,

I got the same error as Sirius and the link in your answer is not available anymore. Should I open a new issue or I can also attach my code and mesh file under this issue?

Thanks,
Ru

**Comment by marcomusy** [comment]
Hi Ru,
thanks, yes, it's probably best to open a new issue.
