### ISSUE TITLE
vtkplotter.dolfin.plot() and embedWindow() do not work inside a for loop in jupyter notebook

### ISSUE THREAD

**Issue by SiriusFuenmayor** [marcomusy/vtkplotter#68]
Hi, I am using the docker container version of FENICS with a jupyter notebook. I have a time dependent problem and I would like to plot the solution in every time step like is usually done in fenics examples, but if I put the vtkplotter.dolfin.plot(u) command inside the time for loop using embedWindow(backend='itkwidgets') or embedWindow(backend='k3d') nothing is shown to the screen. 

If I put the command vtkplotter.dolfin.plot(u) outside the for loop at the end, the plot is show successfully.

**Comment by marcomusy** [comment]
Hi, unfortunately this is a general limitation of the notebook environment, it is not possible to redraw the scene on the same canvas from inside a loop :(
