### ISSUE TITLE
add option in vtkplotter.dolfin.plot clearing previous scalarbars and isolines

### ISSUE THREAD

**Issue by SiriusFuenmayor** [marcomusy/vtkplotter#70]
Hi, I am using the add() option in vtkplotter.dolfin.plot to superimpose my solution to the mesh of my problem while iterating in time. It works very nice but the scalarbars and isolines also get superimposed as well making the lectures on the scalarbar unreadable. Is there a way to use the add() option but clearing previous scalarbars and isolines? Of course I have try the vtkplotter.dolfin.clear(actor=()) function but then I get a plot of the mesh alone between every iteration.

![Screenshot from 2019-10-19 01-31-58](https://user-images.githubusercontent.com/8355915/67138425-d648bb00-f210-11e9-89ae-9daab5655fca.png)

after n iterations:

![Screenshot from 2019-10-19 01-32-17](https://user-images.githubusercontent.com/8355915/67138426-db0d6f00-f210-11e9-92f5-f5f266fc92c1.png)

**Comment by marcomusy** [comment]
Scalarbar handling is a bit of nightmare..
You can try to remove the previous scalarbar(s) in the loop with:
```python
vp = plot(mysolution), ...) # this returns the current Plotter object
for sb in vp.scalarbars:
       vp.renderer.RemoveActor(sb)
```

**Comment by SiriusFuenmayor** [comment]
Gracias Marco!
