### ISSUE TITLE
Text actor followcam.

### ISSUE THREAD

**Issue by mahendra-ramajayam** [marcomusy/vtkplotter#72]
Hi Marco

The `followcam ` parameter in `Text` makes the text disappear when True in k3d, vtk or qt. Is there a workaround to make the text always face the camera when rotating.

```python
from vtkplotter import Sphere, Point, show, Text

# Tried in all three renderes
# embedWindow('k3d')
# embedWindow('itk')
# embedWindow(False) 

sp = Sphere().wireframe(True)
pcoords = sp.getPoint(144)
pt = Point(pcoords, r=12, c="white")

tx = Text("my fave\npoint", pcoords, s=0.1, c="lightblue", bc="green", followcam=True)
# tx.followcam = True
show(sp, pt, tx, Text(__doc__), axes=1)
```

Thank you.

**Comment by marcomusy** [comment]
Hi @mahendra-ramajayam 
try the following example:
https://github.com/marcomusy/vtkplotter/blob/master/examples/plotting2d/markpoint.py

![Peek 2019-11-04 18-34](https://user-images.githubusercontent.com/32848391/68143484-d1cf1280-ff31-11e9-9594-387ba59587ce.gif)

Note that this can only work in the standard vtk rendering window, neither k3d nor itkwidgets support this feature.

**Comment by mahendra-ramajayam** [comment]
Works great in the vtk renderer, Thanks Marco.

However, I'm trying to create a custom tetrahedron axis. I would like the axis labels to face the camera.
![K3D-1572992176623](https://user-images.githubusercontent.com/2786669/68251036-6f335f00-0076-11ea-8719-35d52cd5ac3d.png)
I'm also trying to use ipywidgets to filter data for plotting within the tetrahedron. followCamera() in jupyter notebook rendering would be a great addition.

Thank you

**Comment by marcomusy** [comment]
Hi Mahi, you may only achieve it by creating text in the correct positions along the tet edge manually.
the followCamera() thing does not depend on vtkplotter but on itkwidgets or k3d backends.. i'm not sure if there is any plans for them to implement it..
