### ISSUE TITLE
makeVideo

### ISSUE THREAD

**Issue by NaGenhao** [marcomusy/vtkplotter#80]
The video clips are cool: [video_1](https://youtu.be/6T9FSC2bQDA?t=16), [video_2](https://youtu.be/dVxj8tzx04U?t=221) .

If I want to make a similar video, how should I set the camera parameters(rots and trans or others)? 

Link to [example](https://github.com/marcomusy/vtkplotter/blob/master/examples/other/makeVideo.py)~

**Comment by marcomusy** [comment]
As in the example above you can access the active camera object, or you can 
-  simply use these keywords in the `show()` command: `zoom, viewup, azimuth, elevation, roll` 
- create and pass a `cam=vtkCamera()` to `show(camera=cam)`
- use the `Plotter.moveCamera(cam1, cam2, fraction)` method to smoothly go from one viewpoint to another (use shift-C to dump a template of a specific view) in a loop.

More helper methods are  [cameraFromQuaternion](https://vtkplotter.embl.es/content/vtkplotter/utils.html#camerafromquaternion), [orientedCamera](https://vtkplotter.embl.es/content/vtkplotter/utils.html#orientedcamera).

![image](https://user-images.githubusercontent.com/32848391/70382408-fc125680-195b-11ea-8591-d5787e35d20e.png)
