### ISSUE TITLE
Any option to use vtkplotter without X server?

### ISSUE THREAD

**Issue by MarkusRosen** [marcomusy/vtkplotter#88]
I have been using vtkplotter with success on my local machine, but for a larger project I want to move my code to a server. Problem is, I get the following error:

```
ERROR: In /work/standalone-x64-build/VTK-source/Rendering/OpenGL2/vtkXOpenGLRenderWindow.cxx, line 1223
vtkXOpenGLRenderWindow (0x4fc59e0): bad X server connection. DISPLAY=Aborted (core dumped)
```

I use the option `offscreen=True` and save screenshots of my renderings, but still it does not work. Do you have any idea if this could work in some way without an X server?

**Comment by marcomusy** [comment]
Hi @MarkusRosen  this seems a general limitation of VTK which needs to be build with osmesa support, [see here]( https://discourse.vtk.org/t/how-to-build-vtk-on-a-supercomputer-without-x-server-and-no-root-previliges/377/4).

You can still use all vtkplotter classes to do your analysis and then only save some individual output meshes or volumes to file.

I'm doing some tests now to see if it's doable to export a whole scene in either `npy` `obj` or `x3d` formats to be later visualized..

**Comment by RubendeBruin** [comment]
@MarkusRosen , 
the following works for me:

https://github.com/marcomusy/vtkplotter/issues/64#issuecomment-559979201

that is with the vtk version from conda (8.2.0)

**Comment by MarkusRosen** [comment]
Thank you very much for your quick help! I wasn't able to find this comment. Thanks!
