### ISSUE TITLE
Is there a plan to extend vtkplotter to web using vtk.js?

### ISSUE THREAD

**Issue by Yoorthiziri** [marcomusy/vtkplotter#89]
I've just come across [vtk.js](https://kitware.github.io/vtk-js/docs/) which is web version of the VTK library. Since vtk library (in my opinion) is a low level API compared to vtkplotter, I am wondering if there is a plan (or is it possible) to port vtkplotter to web as well?

Sorry if this is irrelevant
Thank you

**Comment by marcomusy** [comment]
It is not irrelevant at all, but that would certainly be a major project.. so there's no such a plan at the moment!
