### ISSUE TITLE
Bug with isosurface

### ISSUE THREAD

**Issue by qiang-zhang-neu** [marcomusy/vtkplotter#90]
I find there may be a bug with isosurface function. I have a code, and it work fine.

from vtkplotter import *
import numpy as np
mask = np.zeros(shape=[200, 200, 200])
mask[20:80, 50:150, 50:150] = 1
mask[80:150, 80:120, 80:120] = 1
mask[150:170, 50:150, 50:150] = 1
vol = Volume(mask)

iso = vol.isosurface(threshold=1).c('grey').pickable(0)
smoothed_iso = iso.smoothLaplacian(niter=30)

vp = Plotter(verbose=0, bg='black')
vp.show(smoothed_iso)

However, the bug happen when I use mask = np.zeros(shape=[200, 200, 500]) that I can't obtain the surface. The wrong code is:

from vtkplotter import *
import numpy as np
mask = np.zeros(shape=[200, 200, 500])
mask[20:80, 50:150, 50:150] = 1
mask[80:150, 80:120, 80:120] = 1
mask[150:170, 50:150, 50:150] = 1
vol = Volume(mask)

iso = vol.isosurface(threshold=1).c('grey').pickable(0)
smoothed_iso = iso.smoothLaplacian(niter=30)

vp = Plotter(verbose=0, bg='black')
vp.show(smoothed_iso)

What is wrong with my code?

**Comment by marcomusy** [comment]
Please use the master version by doing:
`pip install -U git+https://github.com/marcomusy/vtkplotter.git`
in it the bug should be already fixed.
