### ISSUE TITLE
Can vtkplotter can extract the center line from binary mask just like vmtk?

### ISSUE THREAD

**Issue by zhang-qiang-github** [marcomusy/vtkplotter#91]
I want to extract the center line from a 3D binary mask, just like vmtk (http://www.vmtk.org/tutorials/Centerlines.html). Can vtkplotter extract the center lines? Could you please give me a demo?

**Comment by marcomusy** [comment]
You can use the 1-dimensional _moving least squares_  algorithm of `vtkplotter` to skeletonize a mesh and then spline the resulting points:
```python
from vtkplotter import *

# parameters to play with:
f      = 0.3    # moving least squares fraction of neighbours
niter  = 6      # moving least squares iterations
tol    = 0.02   # minimum point distance as fraction
smooth = 0.1    # spline smoothness paramenter

# built some weird tube for test
ln   = [[sin(x), cos(x), x / 2] for x in arange(0,9,0.1)]
rads = [.3*(cos(6*ir/len(ln)))**2+.1 for ir in range(len(ln))]
tube = Tube(ln, r=rads, res=24, c=None, alpha=0.2)

t = tube
for i in range(niter):
    t = smoothMLS1D(t, f=f).c('white').pointSize(5)
    show(t, at=i, N=niter)

# reduce nr of points by imposing a min distance
t.clean(tol)

# spline the resulting set of points
spl = Spline(t.getPoints(), smooth=smooth)

show(tube, t, spl, axes=1, newPlotter=True)
```
<img width="504" alt="Screenshot 2019-12-25 at 22 03 22" src="https://user-images.githubusercontent.com/32848391/71450519-ebd3e700-2763-11ea-9aad-16e033f7f988.png">
<img width="278" alt="Screenshot 2019-12-25 at 22 02 46" src="https://user-images.githubusercontent.com/32848391/71450525-f8f0d600-2763-11ea-962a-59f00a1d055b.png">

**Comment by zhang-qiang-github** [comment]
Thank you very much for reply. However, how can I decide the value of niter? If the niter is small ( for example 1), I can not extract the center line. If the niter is very large (for example 200), the extract line is not the center line.

**Comment by marcomusy** [comment]
I don't have a mesh to try bifurcation, but in principle it should work.

There will always be a nr of parameters to be   tuned to adapt the algorithm to your specific problem. Such is life :)

**Comment by marcomusy** [comment]
...this is playing around with a test mesh..
```python
from vtkplotter import *

# parameters to play with:
f     = 0.25  # moving least squares fraction of neighbours
niter = 24    # moving least squares iterations
tol   = 0.03  # minimum point distance as fraction

# create a bifurcating mesh
rng = arange(0,1,0.02)
l0  = [vector(0,0,0)*(1-s)+vector(  0,0,1)*s for s in rng]
l0 += [vector(0,0,1)*(1-s)+vector(-.5,0,2)*s for s in rng]
l1  = [vector(0,0,1)*(1-s)+vector(0.5,0,2)*s for s in rng]
# l2  = [vector(0,0,1)*(1-s)+vector(0.1,0.5,2)*s for s in rng]
t0 = Tube(l0, r=0.1, res=24)
t1 = Tube(l1, r=0.1, res=24)
# t2 = Tube(l2, r=0.1, res=24)
tube = booleanOperation(t0,'+',t1)
# tube = booleanOperation(tube,'+',t2)
tube.computeNormals().alpha(0.2).lineWidth(0.1)

t = tube.clone().clean(tol/2)
for i in range(niter):
    t = smoothMLS1D(t, f=f).c('white').pointSize(10)
    show(t, at=i, N=niter, elevation=-1)
t.clean(tol)

show(tube, t, axes=1, newPlotter=True)
```
<img width="346" alt="Screenshot 2019-12-26 at 21 59 19" src="https://user-images.githubusercontent.com/32848391/71490481-4be19080-282b-11ea-834f-4d74e4c3d836.png">
