### ISSUE TITLE
migrating: Actor -> Mesh

### ISSUE THREAD

**Issue by RubendeBruin** [marcomusy/vtkplotter#93]
Hi Marco,
my code was still using .Actor and getActors() which are depreciated in the latest version.

It updating my code as easy as replacing the Actor() [class] by the Mesh and renaming getActors to getMeshes?

**Comment by marcomusy** [comment]
HI Ruben,
Yes that should do the job!

**Comment by RubendeBruin** [comment]
perfect, thanks!
