### ISSUE TITLE
No DICOM magic number found, but file appears to be DICOM

### ISSUE THREAD

**Issue by addriumruss** [marcomusy/vtkplotter#95]
Hi, 
here it comes a problem. 
I use these two lines to load a dicom directory to view it in 3D, which contains 556 dcm files:

volume = load(mydicomdir, threshold=False)
volume.show(bg='black')

but got these error results, and python exit right away.
No DICOM magic number found, but file appears to be DICOM.
Proceeding without caution.
No DICOM magic number found, but file appears to be DICOM.
Proceeding without caution.

When I use Mimics, it can show the 3D view.
How to solve this?

**Comment by addriumruss** [comment]
![2020-01-21_161546](https://user-images.githubusercontent.com/35988105/72786833-93f8a500-3c69-11ea-909b-5555f5479510.png)

**Comment by marcomusy** [comment]
HI, well it looks one of the slices (431 and/or 429) is corrupted.. what if you just remove it from the directory?

**Comment by addriumruss** [comment]
@marcomusy Thanks for response! 
I remove those two files and still not work.
Finally, I copied files from ***.432.1.dcm, ***.432.2.dcm, ...... and the rest to another folder, and test that folder, it worked!
But I'm still confusing, it seems those files endswith ***.372.*.dcm and those ***.432.*.dcm are not one series, they are two series.  If this is the truth, then how to automatically distinguish those series within one piece of CT result?

**Comment by marcomusy** [comment]
Hi @addriumruss - yes if so, it looks like those are completely different sets.. I don't think there is an automatic way of distinguish group of files if they sit in the same dicom directory.

**Comment by addriumruss** [comment]
It might be, the data is provided by the customers. Maybe I need to communicate further with them. 
Thanks again.
