### ISSUE TITLE
working with vtkplotter.show()

### ISSUE THREAD

**Issue by ifermion** [marcomusy/vtkplotter#97]
Hi,

First of all, thanks a lot for sharing what seems to be such an interactive python library for data visualisation. I just discovered vtkplotter and try to use this to visualise my results more meaningfully. However, I think I've got a quick naive question. 

When I tried to load a .obj mesh and visualise it using vtkplotter.show(), it doesn't launch the visual graphic. Instead it give something like following, which according to my idea contains some meta data of the visual.

`In [6]: show(m)

Out[6]: Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[0.012851721776526668, 0.01323173118929217, 0.6199803058828682, 0.0036249905824661255, 0.004004999995231628, 0.004834994673728943, 0, 1, 0], camera_auto_fit=False, camera_fov=60.0, fps=25.0, fps_meter=False, grid=[-0.2778100073337555, -0.263729989528656, -0.24404999613761902, 0.28505998849868774, 0.27173998951911926, 0.2537199854850769], height=500, lighting=1.2, mode='view', object_ids=[112670800472], screenshot_scale=2.0)`

Any idea what I'm missing here ?

Thank you in advance for your time.

**Comment by marcomusy** [comment]
Hello, thanks for your interest! I guess you are trying it from a `jupyter notebook` session.
if so it might be due to the jupyter environment (i'm aware it doesn't work with jupyter lab).
You can still try with adding:
```python
from vtkplotter import embedWindow

# either
embedWindow(False)
# or
embedWindow('2d') # for a static image
```

**Comment by ifermion** [comment]
Hi,

I'm trying from a macbook terminal and I tried both of your solutions. But it doesn't seem to work and leaves me with the following message.

X Error in show(): wrong renderer index 0

Any thoughts ?

**Comment by marcomusy** [comment]
By chance are you trying to create more than one rendering window (that is not supported in notebooks.. I should add a warning message..)?
Can you post the script that gives you the error message?

**Comment by ifermion** [comment]
well, I'm no longer able to reproduce the same error. I tried to visualise a simple shapemodel of a cube. Here are the commands I used and the outputs that I got.

`In [3]: a = vtkplotter.load('cube.obj')`

`In [4]: a?`

`Mesh 
           file: cube.obj
          color: gold, rgb=(1.00, 0.843, 0), alpha=1.0
         points: 8
          cells: 12
       polygons: 12
       position: (0.0, 0.0, 0.0)
 center of mass: (000)
   average size: 0.866025
  diagonal size: 1.73205
           area: 6.00000
         volume: 1.00000
         bounds: x=(-0.500, 0.500) y=(-0.500, 0.500) z=(-0.500, 0.500)
        scalars: no point or cell scalars are present.
`

`In [5]: vtkplotter.show(a)`

`Out[5]: Plot(antialias=3, axes=['x', 'y', 'z'], axes_helper=1.0, background_color=16777215, camera=[0.017320508075688773, 0.017320508075688773, 1.1547057655884772, 0.0, 0.0, 0.0, 0, 1, 0], camera_auto_fit=False, camera_fov=60.0, fps_meter=False, grid=[-0.5, -0.5, -0.5, 0.5, 0.5, 0.5], height=500, lighting=1.2, object_ids=[140241989638968], screenshot_scale=2.0)
`

There was no visual seen. However when I did `vtkplotter cube.obj ` on the terminal, the shape model could be seen with the vtk window popping up. 
` vtkplotter 2020.0.2 | vtk 8.1.2 | python 3.6 | press h for help.`

I'm intrigued why the ipython is not able to launch the vtk window.

**Comment by marcomusy** [comment]
Uhm.. that's pretty weird..
This happens in jupyterlab not on jupyter notebook. From Out[5] I see you are using the K3D backend.
Other options are 
`embedWindow('itk')`
`embedWindow('panel')`
`embedWindow('2d')`
`embedWindow(False)`
I'll give it a try on my macbook too.

**Comment by ifermion** [comment]
Now I think the issue is related to ipython. I'm still not able to make it run inside ipython. But it works just fine when called from the terminal without launching the ipython console. Thanks anyway for your help in trying to isolate the issue.
